SELECT 
T0."DocDate",
T0.NumAtCard	"Referencia",
T0."DocNum",
T0."U_BPP_MDSD" "Serie Documento",
T0."U_BPP_MDCD" "Correlativo Documento",
T0."U_BPP_MDTD" "Tipo Documento",
CASE 
	WHEN T0."U_IDC_FESTADO"='PE' THEN 'DOC. PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='DS' THEN 'DOC. EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='DE' THEN 'DOC. CON ERROR'
	WHEN T0."U_IDC_FESTADO"='DA' THEN 'DOC. APROBADO'
	WHEN T0."U_IDC_FESTADO"='DR' THEN 'DOC. RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='DC' THEN 'DOC. CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='RP' THEN 'RESUMEN PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='RS' THEN 'RESUMEN EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='RE' THEN 'RESUMEN CON ERROR'
	WHEN T0."U_IDC_FESTADO"='RA' THEN 'RESUMEN APROBADO'
	WHEN T0."U_IDC_FESTADO"='RR' THEN 'RESUMEN RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='RC' THEN 'RESUMEN CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BP' THEN 'COM. BAJA PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='BC' THEN 'COM. BAJA CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BR' THEN 'COM. BAJA RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='BA' THEN 'COM. BAJA APROBADO'
	WHEN T0."U_IDC_FESTADO"='BE' THEN 'COM. BAJA CON ERROR'
	WHEN T0."U_IDC_FESTADO"='BS' THEN 'COM. BAJA EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='IN' THEN 'INTERNO'
END "Estado",
t0."U_IDC_FERESP", 
T0."LicTradNum" "Documento Identidad",
T0."CardName" "Nombre/Razón Social",
T0."DocEntry",
T0."ObjType"
FROM OINV T0
WHERE T0.CANCELED IN ('N','Y') AND T0.DocDate>='20210308' --AND T0."U_BPP_MDTD" IN ('01','03','07','08') AND LEFT(T0."U_BPP_MDSD",1) IN('F','B')
AND (T0."U_IDC_FESTADO" = 'DE' OR (T0."U_IDC_FESTADO" = 'PE' AND U_IDC_FERESP IS NULL))

UNION ALL

SELECT 
T0."DocDate",
T0.NumAtCard	"Referencia",
T0."DocNum",
T0."U_BPP_MDSD" "Serie Documento",
T0."U_BPP_MDCD" "Correlativo Documento",
T0."U_BPP_MDTD" "Tipo Documento",
CASE 
	WHEN T0."U_IDC_FESTADO"='PE' THEN 'DOC. PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='DS' THEN 'DOC. EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='DE' THEN 'DOC. CON ERROR'
	WHEN T0."U_IDC_FESTADO"='DA' THEN 'DOC. APROBADO'
	WHEN T0."U_IDC_FESTADO"='DR' THEN 'DOC. RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='DC' THEN 'DOC. CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='RP' THEN 'RESUMEN PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='RS' THEN 'RESUMEN EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='RE' THEN 'RESUMEN CON ERROR'
	WHEN T0."U_IDC_FESTADO"='RA' THEN 'RESUMEN APROBADO'
	WHEN T0."U_IDC_FESTADO"='RR' THEN 'RESUMEN RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='RC' THEN 'RESUMEN CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BP' THEN 'COM. BAJA PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='BC' THEN 'COM. BAJA CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BR' THEN 'COM. BAJA RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='BA' THEN 'COM. BAJA APROBADO'
	WHEN T0."U_IDC_FESTADO"='BE' THEN 'COM. BAJA CON ERROR'
	WHEN T0."U_IDC_FESTADO"='BS' THEN 'COM. BAJA EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='IN' THEN 'INTERNO'
END "Estado",
t0."U_IDC_FERESP", 
T0."LicTradNum" "Documento Identidad",
T0."CardName" "Nombre/Razón Social",
T0."DocEntry",
T0."ObjType"
FROM ODPI T0
WHERE T0.CANCELED IN ('N','Y') AND T0.DocDate>='20210308' --AND T0."U_BPP_MDTD" IN ('01','03','07','08') AND LEFT(T0."U_BPP_MDSD",1) IN('F','B')
AND (T0."U_IDC_FESTADO" = 'DE' OR (T0."U_IDC_FESTADO" = 'PE' AND U_IDC_FERESP IS NULL))

UNION ALL

SELECT 
T0."DocDate",
T0.NumAtCard	"Referencia",
T0."DocNum",
T0."U_BPP_MDSD" "Serie Documento",
T0."U_BPP_MDCD" "Correlativo Documento",
T0."U_BPP_MDTD" "Tipo Documento",
CASE 
	WHEN T0."U_IDC_FESTADO"='PE' THEN 'DOC. PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='DS' THEN 'DOC. EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='DE' THEN 'DOC. CON ERROR'
	WHEN T0."U_IDC_FESTADO"='DA' THEN 'DOC. APROBADO'
	WHEN T0."U_IDC_FESTADO"='DR' THEN 'DOC. RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='DC' THEN 'DOC. CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='RP' THEN 'RESUMEN PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='RS' THEN 'RESUMEN EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='RE' THEN 'RESUMEN CON ERROR'
	WHEN T0."U_IDC_FESTADO"='RA' THEN 'RESUMEN APROBADO'
	WHEN T0."U_IDC_FESTADO"='RR' THEN 'RESUMEN RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='RC' THEN 'RESUMEN CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BP' THEN 'COM. BAJA PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='BC' THEN 'COM. BAJA CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BR' THEN 'COM. BAJA RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='BA' THEN 'COM. BAJA APROBADO'
	WHEN T0."U_IDC_FESTADO"='BE' THEN 'COM. BAJA CON ERROR'
	WHEN T0."U_IDC_FESTADO"='BS' THEN 'COM. BAJA EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='IN' THEN 'INTERNO'
END "Estado",
t0."U_IDC_FERESP", 
T0."LicTradNum" "Documento Identidad",
T0."CardName" "Nombre/Razón Social",
T0."DocEntry",
T0."ObjType"
FROM ORIN T0
WHERE T0.CANCELED IN ('N','Y') AND T0.DocDate>='20210308' --AND T0."U_BPP_MDTD" IN ('01','03','07','08') AND LEFT(T0."U_BPP_MDSD",1) IN('F','B')
AND (T0."U_IDC_FESTADO" = 'DE' OR (T0."U_IDC_FESTADO" = 'PE' AND U_IDC_FERESP IS NULL))

UNION ALL

SELECT 
T0."DocDate",
T0.NumAtCard	"Referencia",
T0."DocNum",
T0."U_BPP_MDSD" "Serie Documento",
T0."U_BPP_MDCD" "Correlativo Documento",
T0."U_BPP_MDTD" "Tipo Documento",
CASE 
	WHEN T0."U_IDC_FESTADO"='PE' THEN 'DOC. PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='DS' THEN 'DOC. EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='DE' THEN 'DOC. CON ERROR'
	WHEN T0."U_IDC_FESTADO"='DA' THEN 'DOC. APROBADO'
	WHEN T0."U_IDC_FESTADO"='DR' THEN 'DOC. RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='DC' THEN 'DOC. CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='RP' THEN 'RESUMEN PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='RS' THEN 'RESUMEN EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='RE' THEN 'RESUMEN CON ERROR'
	WHEN T0."U_IDC_FESTADO"='RA' THEN 'RESUMEN APROBADO'
	WHEN T0."U_IDC_FESTADO"='RR' THEN 'RESUMEN RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='RC' THEN 'RESUMEN CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BP' THEN 'COM. BAJA PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='BC' THEN 'COM. BAJA CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BR' THEN 'COM. BAJA RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='BA' THEN 'COM. BAJA APROBADO'
	WHEN T0."U_IDC_FESTADO"='BE' THEN 'COM. BAJA CON ERROR'
	WHEN T0."U_IDC_FESTADO"='BS' THEN 'COM. BAJA EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='IN' THEN 'INTERNO'
END "Estado",
t0."U_IDC_FERESP", 
T0."LicTradNum" "Documento Identidad",
T0."CardName" "Nombre/Razón Social",
T0."DocEntry",
T0."ObjType"
FROM ODLN T0
WHERE T0.CANCELED IN ('N','Y') AND T0.DocDate>='20210308' --AND T0."U_BPP_MDTD" IN ('01','03','07','08') AND LEFT(T0."U_BPP_MDSD",1) IN('F','B')
AND (T0."U_IDC_FESTADO" = 'DE' OR (T0."U_IDC_FESTADO" = 'PE' AND U_IDC_FERESP IS NULL))

UNION ALL

SELECT 
T0."DocDate",
T0."U_BPP_MDTD"+''+T0."U_BPP_MDSD"+'-'+T0."U_BPP_MDCD"	"Referencia",
T0."DocNum",
T0."U_BPP_MDSD" "Serie Documento",
T0."U_BPP_MDCD" "Correlativo Documento",
T0."U_BPP_MDTD" "Tipo Documento",
CASE 
	WHEN T0."U_IDC_FESTADO"='PE' THEN 'DOC. PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='DS' THEN 'DOC. EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='DE' THEN 'DOC. CON ERROR'
	WHEN T0."U_IDC_FESTADO"='DA' THEN 'DOC. APROBADO'
	WHEN T0."U_IDC_FESTADO"='DR' THEN 'DOC. RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='DC' THEN 'DOC. CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='RP' THEN 'RESUMEN PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='RS' THEN 'RESUMEN EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='RE' THEN 'RESUMEN CON ERROR'
	WHEN T0."U_IDC_FESTADO"='RA' THEN 'RESUMEN APROBADO'
	WHEN T0."U_IDC_FESTADO"='RR' THEN 'RESUMEN RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='RC' THEN 'RESUMEN CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BP' THEN 'COM. BAJA PENDIENTE'
	WHEN T0."U_IDC_FESTADO"='BC' THEN 'COM. BAJA CORREGIDO'
	WHEN T0."U_IDC_FESTADO"='BR' THEN 'COM. BAJA RECHAZADO'
	WHEN T0."U_IDC_FESTADO"='BA' THEN 'COM. BAJA APROBADO'
	WHEN T0."U_IDC_FESTADO"='BE' THEN 'COM. BAJA CON ERROR'
	WHEN T0."U_IDC_FESTADO"='BS' THEN 'COM. BAJA EN SEGUIMIENTO'
	WHEN T0."U_IDC_FESTADO"='IN' THEN 'INTERNO'
END "Estado",
t0."U_IDC_FERESP", 
T0."LicTradNum" "Documento Identidad",
T0."CardName" "Nombre/Razón Social",
T0."DocEntry",
T0."ObjType"
FROM OWTR T0
WHERE T0.CANCELED IN ('N','Y') AND T0.DocDate>='20210308' --AND T0."U_BPP_MDTD" IN ('01','03','07','08') AND LEFT(T0."U_BPP_MDSD",1) IN('F','B')
AND (T0."U_IDC_FESTADO" = 'DE' OR (T0."U_IDC_FESTADO" = 'PE' AND U_IDC_FERESP IS NULL))