DECLARE @FE_OBJTYPE VARCHAR(5)
DECLARE @FE_DOCENTRY INT
DECLARE cursor_name CURSOR
    FOR SELECT FE_OBJTYPE, FE_DOCENTRY FROM TB_DOCUMENTO;
OPEN cursor_name;
FETCH NEXT FROM cursor_name INTO  @FE_OBJTYPE, @FE_DOCENTRY;
WHILE @@FETCH_STATUS = 0  
    BEGIN
		INSERT TB_DETALLE
		EXEC PLUS_FE_SP_LISTA_LINEA @FE_OBJTYPE, @FE_DOCENTRY
		FETCH NEXT FROM cursor_name INTO @FE_OBJTYPE, @FE_DOCENTRY;
    END;
CLOSE cursor_name;
DEALLOCATE cursor_name;
