CREATE PROCEDURE PLUS_FE_SP_LISTAR_DOCUMENTOS_PENDIENTES
AS BEGIN

DECLARE @ML NVARCHAR(3);

SET @ML = (SELECT TOP 1  ISNULL(T0."MainCurncy",'')   FROM OADM T0);

SELECT *,
	"ES_PAGO_CREDITO"		= CASE WHEN "DOC_CODIGO_MEDPAGO" = 'CREDITO' THEN 'TRUE' ELSE 'FALSE' END,
	"ES_DESCUENTO_GLOBAL"	= CASE WHEN "IMPORTE_DESCUENTO_GLOBAL" <> 0 THEN 'TRUE' ELSE 'FALSE' END,
	"ES_FACTURA_CONTINGENCIA"= CASE WHEN "FACTURACION_CONTINGENCIA" = 'Y' THEN 'TRUE' ELSE 'FALSE' END,
	"ES_FACTURA_EXPORTACION"= CASE WHEN "DOC_CODIGO_TIPO_OPERACION" = 'EXPORTACION' THEN 'TRUE' ELSE 'FALSE' END,
	"ES_CONSUME_ANTICIPO"	= CASE WHEN "IMPORTE_ANTICIPO" <> 0 THEN 'TRUE' ELSE 'FALSE' END,
	"ES_CONSUME_GUIA_REMISION" = CASE WHEN "DOC_CANTIDAD_GUIA_REMISION" <> 0 THEN 'TRUE' ELSE 'FALSE' END,
	"INTEGRADOR_TIPO_INTEGRACION" = CASE WHEN "FACTURACION_CONTINGENCIA" = 'Y' THEN 'CONTINGENCIA' ELSE 'OFFLINE' END, --OFFLINE: Responsable del correlativo es la EMPRESA / El valor será CONTIGENCIA cuando se envíen ese tipo de documentos
	"INTEGRADOR_TIPO_REGISTRO" = 'PRECIOS_SIN_IGV',
	"INTEGRADOR_TIPO_PLANTILLA" = '01'
 FROM (
-- BEGIN FACTURAS - BOLETAS
SELECT 
"FACTURACION_ID"		= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"FACTURACION_DOCENTRY"	= T0."DocEntry",
"FACTURACION_OBJTYPE"	= T0."ObjType",
"FACTURACION_DOCNUM"	= T0."DocNum",
"FACTURACION_ESTADO"	= T0."U_IDC_FESTADO",
"FACTURACION_TIPO_SERV_ARTI" = T0."DocType",
"FACTURACION_CONTINGENCIA"	 = T0."U_IDC_ESCONTINGENCIA",

"DOC_TIPO"				= T0."U_BPP_MDTD",
"DOC_SERIE"				= T0."U_BPP_MDSD",
"DOC_CORRELATIVO"		= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"DOC_FECHA_EMISION"		= CONVERT(VARCHAR(10), T0."DocDate", 23),
"DOC_FECHA_VENCIMIENTO"	= CONVERT(VARCHAR(10), T0."DocDueDate", 23),
"DOC_HORA_EMISION"		= '00:00:00',
"DOC_ORDEN_COMPRA"		= T0."U_IDC_OC",
"DOC_TIPO_CAMBIO"		= CASE WHEN T0."DocRate" = 1 THEN 0 ELSE T0."DocRate" END,
"DOC_CODIGO_MONEDA"		= T2."ISOCurrCod",
"DOC_SIMBOLO_MONEDA"	= T2."ChkName",
"DOC_NOMBRE_MONEDA"		= CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END,
"DOC_CONDICION_PAGO"	= CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END,
"DOC_CANTIDAD_ITEM"		= (SELECT COUNT(1) FROM INV1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType"),
"DOC_COMENTARIOS"		= REPLACE(REPLACE(CAST((CASE WHEN ISNULL(T0."Comments",'')=''
												THEN (CASE WHEN ISNULL(T0.U_IDC_TIPFAC,'')='0200' THEN ISNULL(T0."U_IDC_COM_EXPO",'') END)
												ELSE ISNULL(T0."Comments",'')
										  END) AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' '),
"DOC_CODIGO_MEDPAGO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('FPAGO', CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END)),
"DOC_CODIGO_TIPO_OPERACION" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TOPER',ISNULL(T0.U_IDC_TIPFAC,''))),
"DOC_CANTIDAD_GUIA_REMISION"= (SELECT COUNT(1) FROM INV1 WHERE "BaseType"=15 AND "DocEntry"=T0."DocEntry"),

"EMISOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', '6')),
"EMISOR_DOCUMENTO_IDENTIDAD" = T20."TaxIdNum",
"EMISOR_RAZON_SOCIAL"	= T20."PrintHeadr",
"EMISOR_NOMBRE_COMERCIAL" = T20."PrintHeadr",
"EMISOR_TELEFONO"		= T20."Phone1",
"EMISOR_FAX"			= T20."Phone2",
"EMISOR_PAGINA_WEB"		= T21."IntrntAdrs",
"EMISOR_CORREO_ELECTRONICO" = ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com'),
"EMISOR_DIRECCION"		= UPPER(LEFT(ISNULL(CONCAT(T21."Street" , ' ',T21."StreetNo",' ',T21."City", ' ',T21."County", ' ',T22."Name"),''),500)),
"EMISOR_CALLE"			= UPPER(LEFT(ISNULL(T21."Street",''),500)),
"EMISOR_URBANIZACION"	= UPPER(LEFT(ISNULL(T21."Block",''),30)),
"EMISOR_DISTRITO"		= UPPER(ISNULL(T21."City",'')),
"EMISOR_PROVINCIA"		= UPPER(ISNULL(T21."County",'')),
"EMISOR_DEPARTAMENTO"	= UPPER(ISNULL(T22."Name",'')),
"EMISOR_PAIS"			= 'PERU',--UPPER(T20."Country"),
"EMISOR_UBIGEO"			= ISNULL(T21."GlblLocNum",''),

"RECEPTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', T1."U_BPP_BPTD")),
"RECEPTOR_DOCUMENTO_IDENTIDAD" = LEFT(T1."LicTradNum",11),
"RECEPTOR_RAZON_SOCIAL" = T1."CardName",
"RECEPTOR_NOMBRE_COMERCIAL" = T1."CardName",
"RECEPTOR_CORREO_ELECTRONICO" = ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com'),
"RECEPTOR_DIRECCION"	= UPPER(LEFT(ISNULL(T11."Street",'') + ' ' + ISNULL(T11."County",'') + ' ' + ISNULL(T11."City",'')+ ' ' + ISNULL(T12."Name",'')+ ' ' + ISNULL(T14."Name",''),500)),
"RECEPTOR_CALLE"		= UPPER(LEFT(ISNULL(T3."StreetB",ISNULL(T11."Street",'')),100)),
"RECEPTOR_URBANIZACION" = '',--UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30)),
"RECEPTOR_DISTRITO"		= UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),100)),--UPPER(LEFT(ISNULL(T3."CountyB",ISNULL(T11."County",'')),100)),
"RECEPTOR_PROVINCIA"	= UPPER(LEFT(ISNULL(T3."CityB",ISNULL(T11."City",'')),100)),
"RECEPTOR_DEPARTAMENTO" = UPPER(LEFT(ISNULL(T4."Name",ISNULL(T12."Name",'')),100)),
"RECEPTOR_PAIS"			= UPPER(T14."Name"),--UPPER(LEFT(ISNULL(T3."CountryB",T11."Country"),2)),
"RECEPTOR_UBIGEO"		= ISNULL(T3."ZipCodeB",ISNULL(T11."ZipCode",'')),

"REFERENCIA_TIPO"		= NULL,
"REFERENCIA_SERIE"		= NULL,
"REFERENCIA_CORRELATIVO"= NULL,
"REFERENCIA_FECHA_EMISION" = NULL,
"REFERENCIA_CODIGO_MOTIVO" = NULL,
"REFERENCIA_DESCRIPCION_MOTIVO" = NULL,

"DETRACCION_TIPO"		= NULL,
"DETRACCION_CUENTA_BANCO" = NULL,
"DETRACCION_PORCENTAJE" = 0.00,
"DETRACCION_MONTO"		= 0.00,

"RETENCION_CODIGO_REGIMEN" = NULL,
"RETENCION_TASA"		= 0.00,
"RETENCION_IMPORTE_PAGADO" = 0.00,
"RETENCION_IMPORTE_RETENIDO" = 0.00,

"IMPORTE_OPE_GRAVADA"	= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") - CASE WHEN SUM(BB."BaseSum") > 0 THEN ISNULL((SELECT CASE WHEN T2."CurrCode" = @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 WHERE T6."DocEntry"=T0."DocEntry"),0.00) ELSE 0.00 END 
									FROM (SELECT CASE T2."CurrCode" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
											FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
											WHERE C."DocEntry"=T0."DocEntry" AND C."TaxSum"<>0  AND C."RelateType" IN (1,2,3) 
												AND ISNULL((SELECT "TaxOnly" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
												AND (ISNULL((SELECT "U_BPP_OPER" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'')='A'
												OR   ISNULL((SELECT "U_BPP_OPER" FROM INV3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'')='A')
											GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_EXONERADA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") - CASE WHEN SUM(BB."BaseSum") > 0 THEN ISNULL((SELECT CASE WHEN T2."CurrCode" = @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 WHERE T6."DocEntry"=T0."DocEntry"),0.00) ELSE 0.00 END 
									FROM (SELECT CASE T2."CurrCode" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
											FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
											WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
												AND ISNULL((SELECT "TaxOnly" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
												AND (ISNULL((SELECT "U_BPP_OPER" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'')='E'
												OR   ISNULL((SELECT "U_BPP_OPER" FROM INV3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'')='E')
											GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_INAFECTA"	= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") - CASE WHEN SUM(BB."BaseSum") > 0 THEN ISNULL((SELECT CASE WHEN T2."CurrCode" = @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 WHERE T6."DocEntry"=T0."DocEntry"),0.00) ELSE 0.00 END 
									FROM (SELECT CASE T2."CurrCode" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
											FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
											WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
												AND ISNULL((SELECT "TaxOnly" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
												AND (ISNULL((SELECT "U_BPP_OPER" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'')='I'
												OR   ISNULL((SELECT "U_BPP_OPER" FROM INV3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'')='I')
											GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_GRATUITA"	= CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0."DocTotal" - T0."VatSum" ELSE T0."DocTotalFC" - T0."VatSumFC" END ELSE  0.00 END,
"IMPORTE_DESCUENTO_PORCENTAJE" = ISNULL(T0.DiscPrcnt,0.00),
"IMPORTE_DESCUENTO_GLOBAL" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) END,
"IMPORTE_ANTICIPO"		= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE (SELECT CASE T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 WHERE T6."DocEntry"=T0."DocEntry") END,
"IMPORTE_OTROS_CARGOS"	= 0.00,
"IMPORTE_IMPUESTO_PORCENTAJE" = ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0))) FROM OSTA TX1 INNER JOIN INV4 TX2 ON TX1."Code"=TX2."StaCode" WHERE TX2."DocEntry"=T0."DocEntry" GROUP BY TX2."DocEntry"),0.00),
"IMPORTE_IMPUESTO"		= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END,
"IMPORTE_TOTAL"			= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END,0) END
FROM OINV T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode"	= T0."DocCur"
LEFT JOIN INV12 T3 ON T3."DocEntry"	= T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS NVARCHAR(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11."Country"=T14."Code",
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0."U_IDC_FESTADO" IN('PE','DC') AND T0."U_BPP_MDTD" IN ('01','03') AND (LEFT(T0."U_BPP_MDSD",1) IN ('F','B') OR T0."U_IDC_ESCONTINGENCIA"='Y') 
AND T0."DocSubType"<>'DN' AND T0."CANCELED"='N'
-- END FACTURAS - BOLETAS

UNION ALL

-- BEGIN DOCUMENTO ANTICIPO
SELECT
"FACTURACION_ID"		= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"FACTURACION_DOCENTRY"	= T0."DocEntry",
"FACTURACION_OBJTYPE"	= T0."ObjType",
"FACTURACION_DOCNUM"	= T0."DocNum",
"FACTURACION_ESTADO"	= T0."U_IDC_FESTADO",
"FACTURACION_TIPO_SERV_ARTI" = T0."DocType",
"FACTURACION_CONTINGENCIA"	 = T0."U_IDC_ESCONTINGENCIA",

"DOC_TIPO"				= T0."U_BPP_MDTD",
"DOC_SERIE"				= T0."U_BPP_MDSD",
"DOC_CORRELATIVO"		= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"DOC_FECHA_EMISION"		= CONVERT(VARCHAR(10), T0."DocDate", 23),
"DOC_FECHA_VENCIMIENTO"	= CONVERT(VARCHAR(10), T0."DocDueDate", 23),
"DOC_HORA_EMISION"		= '00:00:00',
"DOC_ORDEN_COMPRA"		= T0."U_IDC_OC",
"DOC_TIPO_CAMBIO"		= CASE WHEN T0."DocRate" = 1 THEN 0 ELSE T0."DocRate" END,
"DOC_CODIGO_MONEDA"		= T2."ISOCurrCod",
"DOC_SIMBOLO_MONEDA"	= T2."ChkName",
"DOC_NOMBRE_MONEDA"		= CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END,
"DOC_CONDICION_PAGO"	= CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END,
"DOC_CANTIDAD_ITEM"		= (SELECT COUNT(1) FROM DPI1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType"),
"DOC_COMENTARIOS"		= REPLACE(REPLACE(CAST((CASE WHEN ISNULL(T0."Comments",'')=''
												THEN (CASE WHEN ISNULL(T0.U_IDC_TIPFAC,'')='0200' THEN ISNULL(T0."U_IDC_COM_EXPO",'') END)
												ELSE ISNULL(T0."Comments",'')
										  END) AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' '),
"DOC_CODIGO_MEDPAGO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('FPAGO', CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END)),
"DOC_CODIGO_TIPO_OPERACION" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TOPER',ISNULL(T0.U_IDC_TIPFAC,''))),
"DOC_CANTIDAD_GUIA_REMISION"= 0,

"EMISOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', '6')),
"EMISOR_DOCUMENTO_IDENTIDAD" = T20."TaxIdNum",
"EMISOR_RAZON_SOCIAL"	= T20."PrintHeadr",
"EMISOR_NOMBRE_COMERCIAL" = T20."PrintHeadr",
"EMISOR_TELEFONO"		= T20."Phone1",
"EMISOR_FAX"			= T20."Phone2",
"EMISOR_PAGINA_WEB"		= T21."IntrntAdrs",
"EMISOR_CORREO_ELECTRONICO" = ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com'),
"EMISOR_DIRECCION"		= UPPER(LEFT(ISNULL(CONCAT(T21."Street" , ' ',T21."StreetNo",' ',T21."City", ' ',T21."County", ' ',T22."Name"),''),500)),
"EMISOR_CALLE"			= UPPER(LEFT(ISNULL(T21."Street",''),500)),
"EMISOR_URBANIZACION"	= UPPER(LEFT(ISNULL(T21."Block",''),30)),
"EMISOR_DISTRITO"		= UPPER(ISNULL(T21."City",'')),
"EMISOR_PROVINCIA"		= UPPER(ISNULL(T21."County",'')),
"EMISOR_DEPARTAMENTO"	= UPPER(ISNULL(T22."Name",'')),
"EMISOR_PAIS"			= 'PERU',--UPPER(T20."Country"),
"EMISOR_UBIGEO"			= ISNULL(T21."GlblLocNum",''),

"RECEPTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', T1."U_BPP_BPTD")),
"RECEPTOR_DOCUMENTO_IDENTIDAD" = LEFT(T1."LicTradNum",11),
"RECEPTOR_RAZON_SOCIAL" = T1."CardName",
"RECEPTOR_NOMBRE_COMERCIAL" = T1."CardName",
"RECEPTOR_CORREO_ELECTRONICO" = ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com'),
"RECEPTOR_DIRECCION"	= UPPER(LEFT(ISNULL(T11."Street",'') +' '+ ISNULL(T11."ZipCode",'') + ' '+ISNULL(T11."County",'') + ' '+ISNULL(T12."Name",''),500)),
"RECEPTOR_CALLE"		= UPPER(LEFT(ISNULL(T3."StreetB",ISNULL(T11."Street",'')),100)),
"RECEPTOR_URBANIZACION" = '',--UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30)),
"RECEPTOR_DISTRITO"		= UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),100)),--UPPER(LEFT(ISNULL(T3."CountyB",ISNULL(T11."County",'')),100)),
"RECEPTOR_PROVINCIA"	= UPPER(LEFT(ISNULL(T3."CityB",ISNULL(T11."City",'')),100)),
"RECEPTOR_DEPARTAMENTO" = UPPER(LEFT(ISNULL(T4."Name",ISNULL(T12."Name",'')),100)),
"RECEPTOR_PAIS"			= UPPER(T14."Name"), --UPPER(LEFT(ISNULL(T3."CountryB",T11."Country"),2)),
"RECEPTOR_UBIGEO"		= ISNULL(T3."ZipCodeB",ISNULL(T11."ZipCode",'')),

"REFERENCIA_TIPO"		= NULL,
"REFERENCIA_SERIE"		= NULL,
"REFERENCIA_CORRELATIVO"= NULL,
"REFERENCIA_FECHA_EMISION" = NULL,
"REFERENCIA_CODIGO_MOTIVO" = NULL,
"REFERENCIA_DESCRIPCION_MOTIVO" = NULL,

"DETRACCION_TIPO"		= NULL,
"DETRACCION_CUENTA_BANCO" = NULL,
"DETRACCION_PORCENTAJE" = 0.00,
"DETRACCION_MONTO"		= 0.00,

"RETENCION_CODIGO_REGIMEN" = NULL,
"RETENCION_TASA"		= 0.00,
"RETENCION_IMPORTE_PAGADO" = 0.00,
"RETENCION_IMPORTE_RETENIDO" = 0.00,

"IMPORTE_OPE_GRAVADA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE  ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T0."DocCur" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"<>0  AND C."RelateType" IN (1,2,3) 
										AND ISNULL((SELECT "TaxOnly" FROM DPI1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM DPI1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'')='A'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM DPI3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'') ='A')
									GROUP BY C."LineNum",C."RelateType") BB ),0.00) END,
"IMPORTE_OPE_EXONERADA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE  ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T0."DocCur" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
										AND ISNULL((SELECT "TaxOnly" FROM DPI1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM DPI1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'A')='E'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM DPI3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'A') ='E')
									GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_INAFECTA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE  ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T0."DocCur" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
										AND ISNULL((SELECT "TaxOnly" FROM DPI1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM DPI1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'A')='I'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM DPI3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'A') ='I')
									GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_GRATUITA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0."DocTotal" - T0."VatSum" ELSE T0."DocTotalFC" - T0."VatSumFC" END ELSE  0.00 END,
"IMPORTE_DESCUENTO_PORCENTAJE" = ISNULL(T0.DiscPrcnt,0.00),
"IMPORTE_DESCUENTO_GLOBAL" = ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00),
"IMPORTE_ANTICIPO"		= 0.00,
"IMPORTE_OTROS_CARGOS"	= 0.00,
"IMPORTE_IMPUESTO_PORCENTAJE" = ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0))) FROM OSTA TX1 INNER JOIN DPI4 TX2 ON TX1."Code"=TX2."StaCode" WHERE TX2."DocEntry"=T0."DocEntry" GROUP BY TX2."DocEntry" ),0.00),
"IMPORTE_IMPUESTO" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE  ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END,
"IMPORTE_TOTAL" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END,0) END
FROM ODPI T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN DPI12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS NVARCHAR(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11."Country"=T14."Code",
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0."U_IDC_FESTADO" IN('PE','DC') AND T0."U_BPP_MDTD" IN ('01','03') AND (LEFT(T0."U_BPP_MDSD",1) IN ('F','B') OR T0."U_IDC_ESCONTINGENCIA"='Y') 
AND T0."CANCELED"='N'
-- END DOCUMENTO ANTICIPO

UNION ALL

-- BEGIN NOTAS DE DÉBITO ("DocSubType"='DN')
SELECT 
"FACTURACION_ID"		= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"FACTURACION_DOCENTRY"	= T0."DocEntry",
"FACTURACION_OBJTYPE"	= T0."ObjType",
"FACTURACION_DOCNUM"	= T0."DocNum",
"FACTURACION_ESTADO"	= T0."U_IDC_FESTADO",
"FACTURACION_TIPO_SERV_ARTI" = T0."DocType",
"FACTURACION_CONTINGENCIA"	 = T0."U_IDC_ESCONTINGENCIA",

"DOC_TIPO"				= T0."U_BPP_MDTD",
"DOC_SERIE"				= T0."U_BPP_MDSD",
"DOC_CORRELATIVO"		= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"DOC_FECHA_EMISION"		= CONVERT(VARCHAR(10), T0."DocDate", 23),
"DOC_FECHA_VENCIMIENTO"	= CONVERT(VARCHAR(10), T0."DocDueDate", 23),
"DOC_HORA_EMISION"		= '00:00:00',
"DOC_ORDEN_COMPRA"		= T0."U_IDC_OC",
"DOC_TIPO_CAMBIO"		= CASE WHEN T0."DocRate" = 1 THEN 0 ELSE T0."DocRate" END,
"DOC_CODIGO_MONEDA"		= T2."ISOCurrCod",
"DOC_SIMBOLO_MONEDA"	= T2."ChkName",
"DOC_NOMBRE_MONEDA"		= CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END,
"DOC_CONDICION_PAGO"	= CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END,
"DOC_CANTIDAD_ITEM"		= (SELECT COUNT(1) FROM INV1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType"),
"DOC_COMENTARIOS"		= REPLACE(REPLACE(CAST((CASE WHEN ISNULL(T0."Comments",'')=''
												THEN T0."U_IDC_MOTND"
												ELSE ISNULL(T0."Comments",'')
										  END) AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' '),
"DOC_CODIGO_MEDPAGO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('FPAGO', CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END)),
"DOC_CODIGO_TIPO_OPERACION" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TOPER',ISNULL(T0.U_IDC_TIPFAC,''))),
"DOC_CANTIDAD_GUIA_REMISION"= 0,

"EMISOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', '6')),
"EMISOR_DOCUMENTO_IDENTIDAD" = T20."TaxIdNum",
"EMISOR_RAZON_SOCIAL"	= T20."PrintHeadr",
"EMISOR_NOMBRE_COMERCIAL" = T20."PrintHeadr",
"EMISOR_TELEFONO"		= T20."Phone1",
"EMISOR_FAX"			= T20."Phone2",
"EMISOR_PAGINA_WEB"		= T21."IntrntAdrs",
"EMISOR_CORREO_ELECTRONICO" = ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com'),
"EMISOR_DIRECCION"		= UPPER(LEFT(ISNULL(CONCAT(T21."Street" , ' ',T21."StreetNo",' ',T21."City", ' ',T21."County", ' ',T22."Name"),''),500)),
"EMISOR_CALLE"			= UPPER(LEFT(ISNULL(T21."Street",''),500)),
"EMISOR_URBANIZACION"	= UPPER(LEFT(ISNULL(T21."Block",''),30)),
"EMISOR_DISTRITO"		= UPPER(ISNULL(T21."City",'')),
"EMISOR_PROVINCIA"		= UPPER(ISNULL(T21."County",'')),
"EMISOR_DEPARTAMENTO"	= UPPER(ISNULL(T22."Name",'')),
"EMISOR_PAIS"			= 'PERU',--UPPER(T20."Country"),
"EMISOR_UBIGEO"			= ISNULL(T21."GlblLocNum",''),

"RECEPTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', T1."U_BPP_BPTD")),
"RECEPTOR_DOCUMENTO_IDENTIDAD" = LEFT(T1."LicTradNum",11),
"RECEPTOR_RAZON_SOCIAL" = T1."CardName",
"RECEPTOR_NOMBRE_COMERCIAL" = T1."CardName",
"RECEPTOR_CORREO_ELECTRONICO" = ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com'),
"RECEPTOR_DIRECCION"	= LEFT(UPPER(ISNULL(LEFT(REPLACE(REPLACE(REPLACE(T0."Address",CHAR(10),' ') ,CHAR(13),' ') ,'  ',' '),500),ISNULL(T11."Street",'') + ' ' + ISNULL(T11."County",'') + ' ' + ISNULL(T11."City",'') + ' ' + ISNULL(T12."Name",''))),500),
"RECEPTOR_CALLE"		= UPPER(LEFT(ISNULL(T3."StreetB",ISNULL(T11."Street",'')),100)),
"RECEPTOR_URBANIZACION" = '',--UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30)),
"RECEPTOR_DISTRITO"		= UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),100)),--UPPER(LEFT(ISNULL(T3."CountyB",ISNULL(T11."County",'')),100)),
"RECEPTOR_PROVINCIA"	= UPPER(LEFT(ISNULL(T3."CityB",ISNULL(T11."City",'')),100)),
"RECEPTOR_DEPARTAMENTO" = UPPER(LEFT(ISNULL(T4."Name",ISNULL(T12."Name",'')),100)),
"RECEPTOR_PAIS"			= UPPER(T14."Name"), --UPPER(LEFT(ISNULL(T3."CountryB",T11."Country"),2)),
"RECEPTOR_UBIGEO"		= ISNULL(T3."ZipCodeB",ISNULL(T11."ZipCode",'')),

"REFERENCIA_TIPO"		= (SELECT dbo.PLUS_FE_FN_CATALOGO('TDOCU', T0."U_BPP_MDTO")),
"REFERENCIA_SERIE"		= T0."U_BPP_MDSO",
"REFERENCIA_CORRELATIVO"= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCO")),8),
"REFERENCIA_FECHA_EMISION" = CONVERT(VARCHAR(10), T15."DocDate", 23),
"REFERENCIA_CODIGO_MOTIVO" = NULLIF((SELECT dbo.PLUS_FE_FN_CATALOGO('MOTND', T0."U_IDC_TIPOND")),''),
"REFERENCIA_DESCRIPCION_MOTIVO" = T0."U_IDC_MOTND",

"DETRACCION_TIPO"		= NULL,
"DETRACCION_CUENTA_BANCO" = NULL,
"DETRACCION_PORCENTAJE" = 0.00,
"DETRACCION_MONTO"		= 0.00,

"RETENCION_CODIGO_REGIMEN" = NULL,
"RETENCION_TASA"		= 0.00,
"RETENCION_IMPORTE_PAGADO" = 0.00,
"RETENCION_IMPORTE_RETENIDO" = 0.00,

"IMPORTE_OPE_GRAVADA"	= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T2."CurrCode" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"<>0  AND C."RelateType" IN (1,2,3) 
										AND ISNULL((SELECT "TaxOnly" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'')='A'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM INV3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'') ='A')
									GROUP BY C."LineNum",C."RelateType") BB ),0.00) END,
"IMPORTE_OPE_EXONERADA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T2."CurrCode" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
										AND ISNULL((SELECT "TaxOnly" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'A')='E'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM INV3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'A') ='E')
									GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_INAFECTA"	= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T2."CurrCode" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
										AND ISNULL((SELECT "TaxOnly" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM INV1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'A')='I'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM INV3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'A') ='I')
									GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_GRATUITA"	= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0."DocTotal" - T0."VatSum" ELSE T0."DocTotalFC" - T0."VatSumFC" END ELSE 0.00 END,
"IMPORTE_DESCUENTO_PORCENTAJE" = 0.00, /*En NC el descuento debe estar aplicado (Descuento de linea y global)*/
"IMPORTE_DESCUENTO_GLOBAL" = 0.00, /*En NC el descuento debe estar aplicado (Descuento de linea y global)*/
"IMPORTE_ANTICIPO"		= 0.00,
"IMPORTE_OTROS_CARGOS"	= 0.00,
"IMPORTE_IMPUESTO_PORCENTAJE" = ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0))) FROM OSTA TX1 INNER JOIN INV4 TX2 ON TX1."Code"=TX2."StaCode" WHERE TX2."DocEntry"=T0."DocEntry" GROUP BY TX2."DocEntry"),0.00),
"IMPORTE_IMPUESTO"		= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE  ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END,
"IMPORTE_TOTAL"			= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END,0) END
FROM OINV T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN INV12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS NVARCHAR(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11."Country"=T14."Code"
LEFT JOIN OINV T15 ON T15."NumAtCard"= CASE WHEN T0."DocSubType" = 'DN' THEN T0."U_BPP_MDTO"+T0."U_BPP_MDSO"+'-'+T0."U_BPP_MDCO" ELSE T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+T0."U_BPP_MDCD" END,
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0."U_IDC_FESTADO" IN('PE','DC') AND T0."U_BPP_MDTD" IN ('08') AND (LEFT(T0."U_BPP_MDSD",1) IN ('F','B') OR T0."U_IDC_ESCONTINGENCIA"='Y') 
AND T0."DocSubType"='DN' AND T0."CANCELED"='N'
-- END NOTAS DE DÉBITO ("DocSubType"='DN')

UNION ALL

-- BEGIN NOTA DE CRÉDITO
SELECT 
"FACTURACION_ID"		= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"FACTURACION_DOCENTRY"	= T0."DocEntry",
"FACTURACION_OBJTYPE"	= T0."ObjType",
"FACTURACION_DOCNUM"	= T0."DocNum",
"FACTURACION_ESTADO"	= T0."U_IDC_FESTADO",
"FACTURACION_TIPO_SERV_ARTI" = T0."DocType",
"FACTURACION_CONTINGENCIA"	 = T0."U_IDC_ESCONTINGENCIA",

"DOC_TIPO"				= T0."U_BPP_MDTD",
"DOC_SERIE"				= T0."U_BPP_MDSD",
"DOC_CORRELATIVO"		= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"DOC_FECHA_EMISION"		= CONVERT(VARCHAR(10), T0."DocDate", 23),
"DOC_FECHA_VENCIMIENTO"	= CONVERT(VARCHAR(10), T0."DocDueDate", 23),
"DOC_HORA_EMISION"		= '00:00:00',
"DOC_ORDEN_COMPRA"		= T0."U_IDC_OC",
"DOC_TIPO_CAMBIO"		= CASE WHEN T0."DocRate" = 1 THEN 0 ELSE T0."DocRate" END,
"DOC_CODIGO_MONEDA"		= T2."ISOCurrCod",
"DOC_SIMBOLO_MONEDA"	= T2."ChkName",
"DOC_NOMBRE_MONEDA"		= CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END,
"DOC_CONDICION_PAGO"	= CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END,
"DOC_CANTIDAD_ITEM"		= (SELECT COUNT(1) FROM RIN1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType"),
"DOC_COMENTARIOS"		= REPLACE(REPLACE(CAST((CASE WHEN ISNULL(T0."Comments",'')=''
												THEN T0."U_IDC_MOTNC"
												ELSE ISNULL(T0."Comments",'')
										  END) AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' '),
"DOC_CODIGO_MEDPAGO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('FPAGO', CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END)),
"DOC_CODIGO_TIPO_OPERACION" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TOPER',ISNULL(T0.U_IDC_TIPFAC,''))),
"DOC_CANTIDAD_GUIA_REMISION"= 0,

"EMISOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', '6')),
"EMISOR_DOCUMENTO_IDENTIDAD" = T20."TaxIdNum",
"EMISOR_RAZON_SOCIAL"	= T20."PrintHeadr",
"EMISOR_NOMBRE_COMERCIAL" = T20."PrintHeadr",
"EMISOR_TELEFONO"		= T20."Phone1",
"EMISOR_FAX"			= T20."Phone2",
"EMISOR_PAGINA_WEB"		= T21."IntrntAdrs",
"EMISOR_CORREO_ELECTRONICO" = ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com'),
"EMISOR_DIRECCION"		= UPPER(LEFT(ISNULL(CONCAT(T21."Street" , ' ',T21."StreetNo",' ',T21."City", ' ',T21."County", ' ',T22."Name"),''),500)),
"EMISOR_CALLE"			= UPPER(LEFT(ISNULL(T21."Street",''),500)),
"EMISOR_URBANIZACION"	= UPPER(LEFT(ISNULL(T21."Block",''),30)),
"EMISOR_DISTRITO"		= UPPER(ISNULL(T21."City",'')),
"EMISOR_PROVINCIA"		= UPPER(ISNULL(T21."County",'')),
"EMISOR_DEPARTAMENTO"	= UPPER(ISNULL(T22."Name",'')),
"EMISOR_PAIS"			= 'PERU',--UPPER(T20."Country"),
"EMISOR_UBIGEO"			= ISNULL(T21."GlblLocNum",''),

"RECEPTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', T1."U_BPP_BPTD")),
"RECEPTOR_DOCUMENTO_IDENTIDAD" = LEFT(T1."LicTradNum",11),
"RECEPTOR_RAZON_SOCIAL" = T1."CardName",
"RECEPTOR_NOMBRE_COMERCIAL" = T1."CardName",
"RECEPTOR_CORREO_ELECTRONICO" = ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com'),
"RECEPTOR_DIRECCION"	= UPPER(ISNULL(T11."Street",'') +' '+ ISNULL(T11."ZipCode",'') + ' '+ISNULL(T11."County",'') + ' '+ISNULL(T12."Name",'')),
"RECEPTOR_CALLE"		= UPPER(LEFT(ISNULL(T3."StreetB",ISNULL(T11."Street",'')),100)),
"RECEPTOR_URBANIZACION" = '',--UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30)),
"RECEPTOR_DISTRITO"		= UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),100)),--UPPER(LEFT(ISNULL(T3."CountyB",ISNULL(T11."County",'')),100)),
"RECEPTOR_PROVINCIA"	= UPPER(LEFT(ISNULL(T3."CityB",ISNULL(T11."City",'')),100)),
"RECEPTOR_DEPARTAMENTO" = UPPER(LEFT(ISNULL(T4."Name",ISNULL(T12."Name",'')),100)),
"RECEPTOR_PAIS"			= UPPER(T14."Name"), --UPPER(LEFT(ISNULL(T3."CountryB",T11."Country"),2)),
"RECEPTOR_UBIGEO"		= ISNULL(T3."ZipCodeB",ISNULL(T11."ZipCode",'')),

"REFERENCIA_TIPO"		= (SELECT dbo.PLUS_FE_FN_CATALOGO('TDOCU', T0."U_BPP_MDTO")),
"REFERENCIA_SERIE"		= T0."U_BPP_MDSO",
"REFERENCIA_CORRELATIVO"= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCO")),8),
"REFERENCIA_FECHA_EMISION" = CONVERT(VARCHAR(10), CASE WHEN T15."DocEntry" IS NOT NULL THEN T15."DocDate" WHEN T16."DocEntry" IS NOT NULL THEN T16."DocDate" END, 23),
"REFERENCIA_CODIGO_MOTIVO" = NULLIF((SELECT dbo.PLUS_FE_FN_CATALOGO('MOTNC', T0."U_IDC_TIPONC")),''),
"REFERENCIA_DESCRIPCION_MOTIVO" = T0."U_IDC_MOTNC",

"DETRACCION_TIPO"		= NULL,
"DETRACCION_CUENTA_BANCO" = NULL,
"DETRACCION_PORCENTAJE" = 0.00,
"DETRACCION_MONTO"		= 0.00,

"RETENCION_CODIGO_REGIMEN" = NULL,
"RETENCION_TASA"		= 0.00,
"RETENCION_IMPORTE_PAGADO" = 0.00,
"RETENCION_IMPORTE_RETENIDO" = 0.00,

"IMPORTE_OPE_GRAVADA"	= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T0."DocCur" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"<>0  AND C."RelateType" IN (1,2,3) 
										AND ISNULL((SELECT "TaxOnly" FROM RIN1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM RIN1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'')='A'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM RIN3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'') ='A')
									GROUP BY C."LineNum",C."RelateType") BB ),0.00) END,
"IMPORTE_OPE_EXONERADA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T0."DocCur" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
										AND ISNULL((SELECT "TaxOnly" FROM RIN1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM RIN1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'A')='E'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM RIN3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'A') ='E')
									GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_INAFECTA" = CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL((SELECT SUM(BB."BaseSum") 
							FROM (SELECT CASE T0."DocCur" WHEN @ML THEN MAX(C."BaseSum") ELSE MAX(C."BaseSumFrg") END AS "BaseSum"
									FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
									WHERE C."DocEntry"= T0."DocEntry" AND C."TaxSum"=0 AND C."RelateType" IN (1,2,3)
										AND ISNULL((SELECT "TaxOnly" FROM RIN1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum"),'N')='N' 
										AND (ISNULL((SELECT "U_BPP_OPER" FROM RIN1 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'A')='I'
										OR   ISNULL((SELECT "U_BPP_OPER" FROM RIN3 WHERE "DocEntry"=C."DocEntry" AND "LineNum"=C."LineNum") ,'A') ='I')
									GROUP BY C."LineNum",C."RelateType") BB),0.00) END,
"IMPORTE_OPE_GRATUITA"	= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0."DocTotal" - T0."VatSum" ELSE T0."DocTotalFC" - T0."VatSumFC" END ELSE 0.00 END,
"IMPORTE_DESCUENTO_PORCENTAJE" = 0.00, /*En NC el descuento debe estar aplicado (Descuento de linea y global)*/
"IMPORTE_DESCUENTO_GLOBAL" = 0.00, /*En NC el descuento debe estar aplicado (Descuento de linea y global)*/
"IMPORTE_ANTICIPO"		= 0.00,
"IMPORTE_OTROS_CARGOS"	= 0.00,
"IMPORTE_IMPUESTO_PORCENTAJE" = ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0))) FROM OSTA TX1 INNER JOIN RIN4 TX2 ON TX1."Code"=TX2."StaCode" WHERE TX2."DocEntry"=T0."DocEntry" GROUP BY TX2."DocEntry"),0.00),
"IMPORTE_IMPUESTO"		= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END,
"IMPORTE_TOTAL"			= CASE WHEN ISNULL(T0."U_IDC_TIPVTA",'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END,0) END
FROM ORIN T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN RIN12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS NVARCHAR(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11."Country"=T14."Code"
LEFT JOIN OINV T15 ON T15."NumAtCard"=T0."U_BPP_MDTO"+T0."U_BPP_MDSO"+'-'+T0."U_BPP_MDCO"
LEFT JOIN ODPI T16 ON T16."NumAtCard"=T0."U_BPP_MDTO"+T0."U_BPP_MDSO"+'-'+T0."U_BPP_MDCO",
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0."U_IDC_FESTADO" IN('PE','DC') AND T0."U_BPP_MDTD" IN ('07') AND (LEFT(T0."U_BPP_MDSD",1) IN ('F','B') OR T0."U_IDC_ESCONTINGENCIA"='Y') 
AND T0."CANCELED"='N'
-- END NOTA DE CRÉDITO

/*********************************************************CONTINGENCIA*************************************************/

UNION ALL

-- BEGIN GUIA DE REMISION
SELECT 
"FACTURACION_ID"		= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"FACTURACION_DOCENTRY"	= T0."DocEntry",
"FACTURACION_OBJTYPE"	= T0."ObjType",
"FACTURACION_DOCNUM"	= T0."DocNum",
"FACTURACION_ESTADO"	= T0."U_IDC_FESTADO",
"FACTURACION_TIPO_SERV_ARTI" = T0."DocType",
"FACTURACION_CONTINGENCIA"	 = T0."U_IDC_ESCONTINGENCIA",

"DOC_TIPO"				= T0."U_BPP_MDTD",
"DOC_SERIE"				= T0."U_BPP_MDSD",
"DOC_CORRELATIVO"		= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"DOC_FECHA_EMISION"		= CONVERT(VARCHAR(10), T0."DocDate", 23),
"DOC_FECHA_VENCIMIENTO"	= CONVERT(VARCHAR(10), T0."DocDueDate", 23),
"DOC_HORA_EMISION"		= '00:00:00',
"DOC_ORDEN_COMPRA"		= T0."U_IDC_OC",
"DOC_TIPO_CAMBIO"		= CASE WHEN T0."DocRate" = 1 THEN 0 ELSE T0."DocRate" END,
"DOC_CODIGO_MONEDA"		= T2."ISOCurrCod",
"DOC_SIMBOLO_MONEDA"	= T2."ChkName",
"DOC_NOMBRE_MONEDA"		= CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END,
"DOC_CONDICION_PAGO"	= CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END,
"DOC_CANTIDAD_ITEM"		= (SELECT COUNT(1) FROM DLN1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType"),
"DOC_COMENTARIOS"		= REPLACE(REPLACE(CAST(T0."Comments" AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' '),
"DOC_CODIGO_MEDPAGO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('FPAGO', CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END)),
"DOC_CODIGO_TIPO_OPERACION" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TOPER',ISNULL(T0.U_IDC_TIPFAC,''))),
"DOC_CANTIDAD_GUIA_REMISION"= 0,

"EMISOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', '6')),
"EMISOR_DOCUMENTO_IDENTIDAD" = T20."TaxIdNum",
"EMISOR_RAZON_SOCIAL"	= T20."PrintHeadr",
"EMISOR_NOMBRE_COMERCIAL" = T20."PrintHeadr",
"EMISOR_TELEFONO"		= T20."Phone1",
"EMISOR_FAX"			= T20."Phone2",
"EMISOR_PAGINA_WEB"		= T21."IntrntAdrs",
"EMISOR_CORREO_ELECTRONICO" = ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com'),
"EMISOR_DIRECCION"		= UPPER(LEFT(ISNULL(CONCAT(T21."Street" , ' ',T21."StreetNo",' ',T21."City", ' ',T21."County", ' ',T22."Name"),''),500)),
"EMISOR_CALLE"			= UPPER(LEFT(ISNULL(T21."Street",''),500)),
"EMISOR_URBANIZACION"	= UPPER(LEFT(ISNULL(T21."Block",''),30)),
"EMISOR_DISTRITO"		= UPPER(ISNULL(T21."City",'')),
"EMISOR_PROVINCIA"		= UPPER(ISNULL(T21."County",'')),
"EMISOR_DEPARTAMENTO"	= UPPER(ISNULL(T22."Name",'')),
"EMISOR_PAIS"			= 'PERU',--UPPER(T20."Country"),
"EMISOR_UBIGEO"			= ISNULL(T21."GlblLocNum",''),

"RECEPTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', T1."U_BPP_BPTD")),
"RECEPTOR_DOCUMENTO_IDENTIDAD" = LEFT(T1."LicTradNum",11),
"RECEPTOR_RAZON_SOCIAL" = T1."CardName",
"RECEPTOR_NOMBRE_COMERCIAL" = T1."CardName",
"RECEPTOR_CORREO_ELECTRONICO" = ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com'),
"RECEPTOR_DIRECCION"	= UPPER(LEFT(ISNULL(T11."Street",'') + ' ' + ISNULL(T11."County",'') + ' ' + ISNULL(T11."City",'')+ ' ' + ISNULL(T12."Name",'')+ ' ' + ISNULL(T14."Name",''),500)),
"RECEPTOR_CALLE"		= UPPER(LEFT(ISNULL(T3."StreetB",ISNULL(T11."Street",'')),100)),
"RECEPTOR_URBANIZACION" = '',--UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30)),
"RECEPTOR_DISTRITO"		= UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),100)),--UPPER(LEFT(ISNULL(T3."CountyB",ISNULL(T11."County",'')),100)),
"RECEPTOR_PROVINCIA"	= UPPER(LEFT(ISNULL(T3."CityB",ISNULL(T11."City",'')),100)),
"RECEPTOR_DEPARTAMENTO" = UPPER(LEFT(ISNULL(T4."Name",ISNULL(T12."Name",'')),100)),
"RECEPTOR_PAIS"			= UPPER(T14."Name"), --UPPER(LEFT(ISNULL(T3."CountryB",T11."Country"),2)),
"RECEPTOR_UBIGEO"		= ISNULL(T3."ZipCodeB",ISNULL(T11."ZipCode",'')),

"REFERENCIA_TIPO"		= NULL,
"REFERENCIA_SERIE"		= NULL,
"REFERENCIA_CORRELATIVO"= NULL,
"REFERENCIA_FECHA_EMISION" = NULL,
"REFERENCIA_CODIGO_MOTIVO" = NULL,
"REFERENCIA_DESCRIPCION_MOTIVO" = NULL,

"DETRACCION_TIPO"		= NULL,
"DETRACCION_CUENTA_BANCO" = NULL,
"DETRACCION_PORCENTAJE" = 0.00,
"DETRACCION_MONTO"		= 0.00,

"RETENCION_CODIGO_REGIMEN" = NULL,
"RETENCION_TASA"		= 0.00,
"RETENCION_IMPORTE_PAGADO" = 0.00,
"RETENCION_IMPORTE_RETENIDO" = 0.00,

"IMPORTE_OPE_GRAVADA"	= 0.00,
"IMPORTE_OPE_EXONERADA" = 0.00,
"IMPORTE_OPE_INAFECTA"	= 0.00,
"IMPORTE_OPE_GRATUITA"	= 0.00,
"IMPORTE_DESCUENTO_PORCENTAJE" = 0.00,
"IMPORTE_DESCUENTO_GLOBAL" = 0.00,
"IMPORTE_ANTICIPO"		= 0.00,
"IMPORTE_OTROS_CARGOS"	= 0.00,
"IMPORTE_IMPUESTO_PORCENTAJE" = 0.00,
"IMPORTE_IMPUESTO"		= 0.00,
"IMPORTE_TOTAL"			= 0.00
FROM ODLN T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN DLN12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS NVARCHAR(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11."Country"=T14."Code",
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0."U_IDC_FESTADO" IN('PE','DC') AND LEFT(T0."U_BPP_MDSD",1) IN ('T') AND T0."U_BPP_MDTD" IN ('09')  AND T0."CANCELED"='N'
-- END GUIA DE REMISION


UNION ALL

--BEGIN GUIA DE REMISIÓN DESDE TRANSFERENCIA DE STOCK
SELECT 
"FACTURACION_ID"		= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"FACTURACION_DOCENTRY"	= T0."DocEntry",
"FACTURACION_OBJTYPE"	= T0."ObjType",
"FACTURACION_DOCNUM"	= T0."DocNum",
"FACTURACION_ESTADO"	= T0."U_IDC_FESTADO",
"FACTURACION_TIPO_SERV_ARTI" = T0."DocType",
"FACTURACION_CONTINGENCIA"	 = T0."U_IDC_ESCONTINGENCIA",

"DOC_TIPO"				= T0."U_BPP_MDTD",
"DOC_SERIE"				= T0."U_BPP_MDSD",
"DOC_CORRELATIVO"		= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
"DOC_FECHA_EMISION"		= CONVERT(VARCHAR(10), T0."DocDate", 23),
"DOC_FECHA_VENCIMIENTO"	= CONVERT(VARCHAR(10), T0."DocDueDate", 23),
"DOC_HORA_EMISION"		= '00:00:00',
"DOC_ORDEN_COMPRA"		= T0."U_IDC_OC",
"DOC_TIPO_CAMBIO"		= CASE WHEN T0."DocRate" = 1 THEN 0 ELSE T0."DocRate" END,
"DOC_CODIGO_MONEDA"		= T2."ISOCurrCod",
"DOC_SIMBOLO_MONEDA"	= T2."ChkName",
"DOC_NOMBRE_MONEDA"		= CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END,
"DOC_CONDICION_PAGO"	= CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END,
"DOC_CANTIDAD_ITEM"		= (SELECT COUNT(1) FROM WTR1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType"),
"DOC_COMENTARIOS"		= REPLACE(REPLACE(CAST(T0."Comments" AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' '),
"DOC_CODIGO_MEDPAGO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('FPAGO', CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END)),
"DOC_CODIGO_TIPO_OPERACION" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TOPER',ISNULL(T0.U_IDC_TIPFAC,''))),
"DOC_CANTIDAD_GUIA_REMISION"= 0,

"EMISOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', '6')),
"EMISOR_DOCUMENTO_IDENTIDAD" = T20."TaxIdNum",
"EMISOR_RAZON_SOCIAL"	= T20."PrintHeadr",
"EMISOR_NOMBRE_COMERCIAL" = T20."PrintHeadr",
"EMISOR_TELEFONO"		= T20."Phone1",
"EMISOR_FAX"			= T20."Phone2",
"EMISOR_PAGINA_WEB"		= T21."IntrntAdrs",
"EMISOR_CORREO_ELECTRONICO" = ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com'),
"EMISOR_DIRECCION"		= UPPER(LEFT(ISNULL(CONCAT(T21."Street" , ' ',T21."StreetNo",' ',T21."City", ' ',T21."County", ' ',T22."Name"),''),500)),
"EMISOR_CALLE"			= UPPER(LEFT(ISNULL(T21."Street",''),500)),
"EMISOR_URBANIZACION"	= UPPER(LEFT(ISNULL(T21."Block",''),30)),
"EMISOR_DISTRITO"		= UPPER(ISNULL(T21."City",'')),
"EMISOR_PROVINCIA"		= UPPER(ISNULL(T21."County",'')),
"EMISOR_DEPARTAMENTO"	= UPPER(ISNULL(T22."Name",'')),
"EMISOR_PAIS"			= 'PERU',--UPPER(T20."Country"),
"EMISOR_UBIGEO"			= ISNULL(T21."GlblLocNum",''),

"RECEPTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', T1."U_BPP_BPTD")),
"RECEPTOR_DOCUMENTO_IDENTIDAD" = LEFT(T1."LicTradNum",11),
"RECEPTOR_RAZON_SOCIAL" = T1."CardName",
"RECEPTOR_NOMBRE_COMERCIAL" = T1."CardName",
"RECEPTOR_CORREO_ELECTRONICO" = ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com'),
"RECEPTOR_DIRECCION"	= UPPER(LEFT(ISNULL(T11."Street",'') + ' ' + ISNULL(T11."County",'') + ' ' + ISNULL(T11."City",'')+ ' ' + ISNULL(T12."Name",'')+ ' ' + ISNULL(T14."Name",''),500)),
"RECEPTOR_CALLE"		= UPPER(LEFT(ISNULL(T3."StreetB",ISNULL(T11."Street",'')),100)),
"RECEPTOR_URBANIZACION" = '',--UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30)),
"RECEPTOR_DISTRITO"		= UPPER(LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),100)),--UPPER(LEFT(ISNULL(T3."CountyB",ISNULL(T11."County",'')),100)),
"RECEPTOR_PROVINCIA"	= UPPER(LEFT(ISNULL(T3."CityB",ISNULL(T11."City",'')),100)),
"RECEPTOR_DEPARTAMENTO" = UPPER(LEFT(ISNULL(T4."Name",ISNULL(T12."Name",'')),100)),
"RECEPTOR_PAIS"			= UPPER(T14."Name"),--UPPER(LEFT(ISNULL(T3."CountryB",T11."Country"),2)),
"RECEPTOR_UBIGEO"		= ISNULL(T3."ZipCodeB",ISNULL(T11."ZipCode",'')),

"REFERENCIA_TIPO"		= NULL,
"REFERENCIA_SERIE"		= NULL,
"REFERENCIA_CORRELATIVO"= NULL,
"REFERENCIA_FECHA_EMISION" = NULL,
"REFERENCIA_CODIGO_MOTIVO" = NULL,
"REFERENCIA_DESCRIPCION_MOTIVO" = NULL,

"DETRACCION_TIPO"		= NULL,
"DETRACCION_CUENTA_BANCO" = NULL,
"DETRACCION_PORCENTAJE" = 0.00,
"DETRACCION_MONTO"		= 0.00,

"RETENCION_CODIGO_REGIMEN" = NULL,
"RETENCION_TASA"		= 0.00,
"RETENCION_IMPORTE_PAGADO" = 0.00,
"RETENCION_IMPORTE_RETENIDO" = 0.00,

"IMPORTE_OPE_GRAVADA"	= 0.00,
"IMPORTE_OPE_EXONERADA" = 0.00,
"IMPORTE_OPE_INAFECTA"	= 0.00,
"IMPORTE_OPE_GRATUITA"	= 0.00,
"IMPORTE_DESCUENTO_PORCENTAJE" = 0.00,
"IMPORTE_DESCUENTO_GLOBAL" = 0.00,
"IMPORTE_ANTICIPO"		= 0.00,
"IMPORTE_OTROS_CARGOS"	= 0.00,
"IMPORTE_IMPUESTO_PORCENTAJE" = 0.00,
"IMPORTE_IMPUESTO"		= 0.00,
"IMPORTE_TOTAL"			= 0.00
FROM OWTR T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN WTR12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS NVARCHAR(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11."Country"=T14."Code", 
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0."U_IDC_FESTADO" IN('PE','DC') AND LEFT(T0."U_BPP_MDSD",1) IN ('T') AND T0."U_BPP_MDTD" IN ('09')  AND T0."CANCELED"='N'
--END GUIA DE REMISIÓN DESDE TRANSFERENCIA DE STOCK

) T
	WHERE DATEDIFF(MONTH, "DOC_FECHA_EMISION", GETDATE()) <= 7
END