CREATE PROCEDURE PLUS_FE_SP_LISTAR_ANTICIPOS 
(
@ObjType  VARCHAR(15),
@DocEntry INT
)
AS BEGIN

DECLARE @ML NVARCHAR(3) = (SELECT TOP 1 T0."MainCurncy" FROM OADM T0)

SELECT 
"FACTURACION_ID"		= T4."U_BPP_MDTD"+'-'+T4."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T4."U_BPP_MDCD")),8),
"ANTICIPO_LINEA"		= ROW_NUMBER() OVER (ORDER BY T1."U_BPP_MDTD"+T1."U_BPP_MDSD"+'-'+T1."U_BPP_MDCD"),
"ANTICIPO_TIPO"			= 'FACTURA_EMITIDA_POR_ANTICIPO',--'02',
"ANTICIPO_SERIE"		= T1."U_BPP_MDSD",
"ANTICIPO_CORRELATIVO"	= RIGHT('00000000' + LTRIM(RTRIM(T1."U_BPP_MDCD")),8),
"ANTICIPO_CODIGO_MONEDA"= T2."ISOCurrCod",
"ANTICIPO_TIPO_AFECTACION"	= (SELECT MAX("U_BPP_OPER") FROM DPI1 WHERE "DocEntry" = T0."BaseAbs"),
"ANTICIPO_IMPUESTO"		= CASE WHEN T1."DocCur" = @ML THEN T0."Vat" ELSE T0."VatFc" END,
"ANTICIPO_MONTO"		= CASE WHEN T1."DocCur" = @ML THEN T0."DrawnSum" ELSE T0."DrawnSumFc" END
FROM INV9 T0 INNER JOIN ODPI T1 ON T0."BaseAbs"=T1."DocEntry" 
			 INNER JOIN OCRN T2 ON T1."DocCur"=T2."CurrCode"
			 INNER JOIN OINV T4 ON T0.DocEntry=T4."DocEntry"
WHERE T0."DocEntry"=@DocEntry  AND T0."ObjCode"=@ObjType;
END