CREATE PROCEDURE PLUS_FE_SP_LISTAR_DOCUMENTOS_ENVIADOS
(
@Estado	VARCHAR(2) --ES - Estado SUNAT| EP -Estado PDF
)
AS
BEGIN

SELECT * FROM (
-- BEGIN FACTURA, BOLETA, NOTA DEBITO
SELECT 
	"FACTURACION_ID"= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"FACTURACION_DOCENTRY" = T0."DocEntry",
	"FACTURACION_OBJTYPE"  = T0."ObjType",
	"DOC_TIPO"		= T0."U_BPP_MDTD",
	"DOC_SERIE"		= T0."U_BPP_MDSD",
	"DOC_CORRELATIVO"	= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"DOC_FECHA_EMISION" = CONVERT(VARCHAR(10), T0."DocDate", 23),
	"EMISOR_DOCUMENTO_IDENTIDAD" = T1."TaxIdNum"
FROM OINV T0, OADM T1
WHERE ((@Estado = 'ES' AND T0."U_IDC_FESTADO" IN ('DS','BS')) OR (@Estado = 'EP' AND T0."U_IDC_FESTADO" NOT IN ('IN','PE','DE') AND ISNULL(T0."U_PLUS_ESTADOPDF",'') IN ('','PP','PE')))
AND T0."U_BPP_MDTD" IN ('01','03','07','08') AND T0."CANCELED"='N'
AND T0."U_BPP_MDCD" != 'ANULADO'
AND (LEFT(T0."U_BPP_MDSD",1) IN ('F','B') OR T0."U_IDC_ESCONTINGENCIA"='Y')
-- END FACTURA, BOLETA, NOTA DEBITO 

UNION ALL

-- BEGIN ANTICIPOS
SELECT
	"FACTURACION_ID"= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"FACTURACION_DOCENTRY" = T0."DocEntry",
	"FACTURACION_OBJTYPE"  = T0."ObjType",
	"DOC_TIPO"		= T0."U_BPP_MDTD",
	"DOC_SERIE"		= T0."U_BPP_MDSD",
	"DOC_CORRELATIVO"	= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"DOC_FECHA_EMISION" = CONVERT(VARCHAR(10), T0."DocDate", 23),
	"EMISOR_DOCUMENTO_IDENTIDAD" = T1."TaxIdNum"
FROM ODPI T0, OADM T1
WHERE ((@Estado = 'ES' AND T0."U_IDC_FESTADO" IN ('DS','BS')) OR (@Estado = 'EP' AND T0."U_IDC_FESTADO" NOT IN ('IN','PE','DE') AND ISNULL(T0."U_PLUS_ESTADOPDF",'') IN ('','PP','PE')))
AND T0."U_BPP_MDTD" IN ('01','03') AND T0."CANCELED"='N'
AND T0."U_BPP_MDCD" != 'ANULADO'
AND (LEFT(T0."U_BPP_MDSD",1) IN ('F','B') OR T0."U_IDC_ESCONTINGENCIA"='Y')
-- END ANTICIPOS

UNION ALL

-- BEGIN NOTA DE CRÉDITO
SELECT
	"FACTURACION_ID"= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"FACTURACION_DOCENTRY" = T0."DocEntry",
	"FACTURACION_OBJTYPE"  = T0."ObjType",
	"DOC_TIPO"		= T0."U_BPP_MDTD",
	"DOC_SERIE"		= T0."U_BPP_MDSD",
	"DOC_CORRELATIVO"	= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"DOC_FECHA_EMISION" = CONVERT(VARCHAR(10), T0."DocDate", 23),
	"EMISOR_DOCUMENTO_IDENTIDAD" = T1."TaxIdNum"
FROM ORIN T0, OADM T1
WHERE ((@Estado = 'ES' AND T0."U_IDC_FESTADO" IN ('DS','BS')) OR (@Estado = 'EP' AND T0."U_IDC_FESTADO" NOT IN ('IN','PE','DE') AND ISNULL(T0."U_PLUS_ESTADOPDF",'') IN ('','PP','PE')))
AND T0."U_BPP_MDTD" IN ('07') AND T0."CANCELED"='N'
AND T0."U_BPP_MDCD" != 'ANULADO'
AND (LEFT(T0."U_BPP_MDSD",1) IN ('F','B') OR T0."U_IDC_ESCONTINGENCIA"='Y')
-- END NOTA DE CRÉDITO

UNION ALL

-- BEGIN GUIA REMISION VENTA
SELECT
	"FACTURACION_ID"= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"FACTURACION_DOCENTRY" = T0."DocEntry",
	"FACTURACION_OBJTYPE"  = T0."ObjType",
	"DOC_TIPO"		= T0."U_BPP_MDTD",
	"DOC_SERIE"		= T0."U_BPP_MDSD",
	"DOC_CORRELATIVO"	= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"DOC_FECHA_EMISION" = CONVERT(VARCHAR(10), T0."DocDate", 23),
	"EMISOR_DOCUMENTO_IDENTIDAD" = T1."TaxIdNum"
FROM ODLN T0, OADM T1
WHERE ((@Estado = 'ES' AND T0."U_IDC_FESTADO" IN ('DS','BS')) OR (@Estado = 'EP' AND T0."U_IDC_FESTADO" NOT IN ('IN','PE','DE') AND ISNULL(T0."U_PLUS_ESTADOPDF",'') IN ('','PP','PE')))
AND T0."U_BPP_MDTD" IN ('09') AND T0."CANCELED"='N'
AND T0."U_BPP_MDCD" != 'ANULADO'
AND (LEFT(T0."U_BPP_MDSD",1) IN ('T') OR T0."U_IDC_ESCONTINGENCIA"='Y')
-- END GUIA REMISION VENTA

UNION ALL

-- BEGIN GUIA REMISION TRASNFERENCIA
SELECT
	"FACTURACION_ID"= T0."U_BPP_MDTD"+'-'+T0."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"FACTURACION_DOCENTRY" = T0."DocEntry",
	"FACTURACION_OBJTYPE"  = T0."ObjType",
	"DOC_TIPO"		= T0."U_BPP_MDTD",
	"DOC_SERIE"		= T0."U_BPP_MDSD",
	"DOC_CORRELATIVO"	= RIGHT('00000000' + LTRIM(RTRIM(T0."U_BPP_MDCD")),8),
	"DOC_FECHA_EMISION" = CONVERT(VARCHAR(10), T0."DocDate", 23),
	"EMISOR_DOCUMENTO_IDENTIDAD" = T1."TaxIdNum"
FROM OWTR T0, OADM T1
WHERE ((@Estado = 'ES' AND T0."U_IDC_FESTADO" IN ('DS','BS')) OR (@Estado = 'EP' AND T0."U_IDC_FESTADO" NOT IN ('IN','PE','DE') AND ISNULL(T0."U_PLUS_ESTADOPDF",'') IN ('','PP','PE')))
AND T0."U_BPP_MDTD" IN ('09') AND T0."CANCELED"='N'
AND T0."U_BPP_MDCD" != 'ANULADO'
AND (LEFT(T0."U_BPP_MDSD",1) IN ('T') OR T0."U_IDC_ESCONTINGENCIA"='Y')
-- END GUIA REMISION TRASNFERENCIA
) T01 WHERE DATEDIFF(MONTH, "DOC_FECHA_EMISION", GETDATE()) <= 2 --AND CAST("DOC_FECHA_EMISION" AS DATE) >= '20210301' --Verificado hasta 24-04-2022 y parte del 25-04-2022

END