CREATE PROCEDURE PLUS_FE_SP_DATOS_EMISOR
AS BEGIN
SELECT  
"EMISOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CLOSE2U_CATALOGO('DIDEN', '6')),
"EMISOR_DOCUMENTO_IDENTIDAD" = "TaxIdNum",
"EMISOR_RAZON_SOCIAL"		 = "PrintHeadr",
"EMISOR_NOMBRE_COMERCIAL"	 = "PrintHeadr",
"EMISOR_CORREO_ELECTRONICO"  = ISNULL("E_Mail",'facturacion.peru@winnerssport.com')
FROM  OADM

END