CREATE PROCEDURE PLUS_FE_SP_DATOS_GUIA_REMISION
(
@ObjType	VARCHAR(15),
@DocEntry	INT
)
AS BEGIN

DECLARE @ML VARCHAR(3) = (SELECT TOP 1 T0."MainCurncy" FROM OADM T0);

SELECT DISTINCT
"FACTURACION_ID"			= T1."U_BPP_MDTD"+'-'+T1."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T1."U_BPP_MDCD")),8),
"GUIA_FECHA_INICIO_TRASLADO"= CONVERT(VARCHAR(10), T1."U_BPP_FIT", 23),
"GUIA_MODALIDAD_TRASLADO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('MODTR',T1."U_BPP_MT")),
"GUIA_NUMERO_BULTO"			= ISNULL(T1."U_BPP_NBP",0.00),
"GUIA_UNIDAD_MEDIDA"		= (SELECT dbo.PLUS_FE_FN_CATALOGO('UNDME','KGM')),
"GUIA_PESO"					= T1."U_BPP_PBT",
"GUIA_CODIGO_PUERTO"		= T1."U_BPP_CDAD", 
"GUIA_NUMERO_CONTENEDOR"	= NULL,
"GUIA_INDICADOR_TRANSBORDO_PROGRAMADO" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TRPRO',T1."U_BPP_TRSB")),
"GUIA_CODIGO_MOTIVO"		= (SELECT dbo.PLUS_FE_FN_CATALOGO('MOTTC',T1."U_BPP_MDMT")),
"GUIA_DESCRIPCION_MOTIVO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('MOTTD',T1."U_BPP_MDMT")),
"PUNTO_PARTIDA_DIRECCION"	= UPPER((SELECT TOP 1 CONCAT(TX1."Street",' ',TX1."StreetNo",' ',TX1."Block") FROM DLN1 TX0 INNER JOIN OWHS TX1 ON TX1."WhsCode"=TX0."WhsCode" WHERE TX0."DocEntry"=@DocEntry AND TX0."ObjType"=@ObjType)),
"PUNTO_PARTIDA_UBIGEO"		= (SELECT TOP 1 ISNULL(TX1."GlblLocNum",'101010') FROM DLN1 TX0 INNER JOIN OWHS TX1 ON TX1."WhsCode"=TX0."WhsCode" WHERE TX0."DocEntry"=@DocEntry AND TX0."ObjType"=@ObjType),
"PUNTO_LLEGADA_DIRECCION"	= UPPER(CONCAT(T6."StreetS",' ',ISNULL(T6."StreetNoS",''),' ',ISNULL(T6."BlockS",''))),
"PUNTO_LLEGADA_UBIGEO"		= ISNULL(T7."GlblLocNum",'101010'),
"TRANSPORTISTA_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', CASE WHEN T1.U_BPP_MDNT IS NOT NULL THEN '6' ELSE '1' END)),
"TRANSPORTISTA_DOCUMENTO_IDENTIDAD" = ISNULL(T1.U_BPP_NDOCT,'99999999'),
"TRANSPORTISTA_RAZON_SOCIAL" = ISNULL(T1.U_BPP_MDNT,'INTERNO'),
"CONDUCTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', ISNULL(T1."U_BPP_TDC",'1'))),
"CONDUCTOR_DOCUMENTO_IDENTIDAD" = ISNULL(T1."U_BPP_DCON",'99999999'),
"CONDUCTOR_RAZON_SOCIAL" = ISNULL(T8."Name",'INTERNO'),
"CONDUCTOR_LICENCIA_CONDUCIR" = T1."U_BPP_MDFC",
"VEHICULO_MARCA" = T1."U_BPP_MDVN",
"VEHICULO_NUMERO_PLACA" = T1."U_BPP_MDVC",
"VEHICULO_CERTIFICADO_INSCRIPCION" = NULL
FROM ODLN T1
LEFT JOIN DLN1 T2 ON T1."DocEntry"=T2."DocEntry"
LEFT JOIN OITM T3 ON T2."ItemCode"=T3."ItemCode"
LEFT JOIN OCRD T5 ON T1."CardCode" = T5."CardCode"
LEFT JOIN DLN12 T6 ON T1."DocEntry"=T6."DocEntry"
LEFT JOIN CRD1 T7 ON T5."CardCode"=T7."CardCode"
LEFT JOIN "@BPP_CONDUC" T8 ON T1."U_BPP_MDFN"=T8."Code"
WHERE T1."DocEntry"= @DocEntry	AND  T1."ObjType"= @objtype

UNION ALL

SELECT DISTINCT
"FACTURACION_ID"			= T1."U_BPP_MDTD"+'-'+T1."U_BPP_MDSD"+'-'+RIGHT('00000000' + LTRIM(RTRIM(T1."U_BPP_MDCD")),8),
"GUIA_FECHA_INICIO_TRASLADO"= CONVERT(VARCHAR(10), T1."U_BPP_FIT", 23),
"GUIA_MODALIDAD_TRASLADO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('MODTR',T1."U_BPP_MT")),
"GUIA_NUMERO_BULTO"			= ISNULL(T1."U_BPP_NBP",0.00),
"GUIA_UNIDAD_MEDIDA"		= (SELECT dbo.PLUS_FE_FN_CATALOGO('UNDME','KGM')),
"GUIA_PESO"					= T1."U_BPP_PBT",
"GUIA_CODIGO_PUERTO"		= T1."U_BPP_CDAD",
"GUIA_NUMERO_CONTENEDOR"	= NULL,
"GUIA_INDICADOR_TRANSBORDO_PROGRAMADO" = (SELECT dbo.PLUS_FE_FN_CATALOGO('TRPRO',T1."U_BPP_TRSB")),
"GUIA_CODIGO_MOTIVO"		= (SELECT dbo.PLUS_FE_FN_CATALOGO('MOTTC',T1."U_BPP_MDMT")),
"GUIA_DESCRIPCION_MOTIVO"	= (SELECT dbo.PLUS_FE_FN_CATALOGO('MOTTD',T1."U_BPP_MDMT")),
"PUNTO_PARTIDA_DIRECCION"	= (SELECT TOP 1 CONCAT(ISNULL(TX1."Street",''),' ',ISNULL(TX1."StreetNo",''),' ',ISNULL(TX1."Block",'')) FROM WTR1 TX0 INNER JOIN OWHS TX1 ON TX1."WhsCode"=TX0."FromWhsCod" WHERE TX0."DocEntry"=@DocEntry AND TX0."ObjType"=@ObjType),
"PUNTO_PARTIDA_UBIGEO"		= (SELECT TOP 1 ISNULL(TX1."GlblLocNum",'101010') FROM WTR1 TX0 INNER JOIN OWHS TX1 ON TX1."WhsCode"=TX0."FromWhsCod" WHERE TX0."DocEntry"=@DocEntry AND TX0."ObjType"=@ObjType),
"PUNTO_LLEGADA_DIRECCION"	= (SELECT TOP 1 CONCAT(ISNULL(TX1."Street",''),' ',ISNULL(TX1."StreetNo",''),' ',ISNULL(TX1."Block",'')) FROM WTR1 TX0 INNER JOIN OWHS TX1 ON TX1."WhsCode"=TX0."WhsCode" WHERE TX0."DocEntry"=@DocEntry AND TX0."ObjType"=@ObjType),
"PUNTO_LLEGADA_UBIGEO"		= (SELECT TOP 1 ISNULL(TX1."GlblLocNum",'101010') FROM WTR1 TX0 INNER JOIN OWHS TX1 ON TX1."WhsCode"=TX0."WhsCode" WHERE TX0."DocEntry"=@DocEntry AND TX0."ObjType"=@ObjType),
"TRANSPORTISTA_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', CASE WHEN T1.U_BPP_MDNT IS NOT NULL THEN '6' ELSE '1' END)),
"TRANSPORTISTA_DOCUMENTO_IDENTIDAD" = ISNULL(T1.U_BPP_NDOCT,'99999999'),
"TRANSPORTISTA_RAZON_SOCIAL" = ISNULL(T1.U_BPP_MDNT,'INTERNO'),
"CONDUCTOR_TIPO_DOCUMENTO_IDENTIDAD" = (SELECT dbo.PLUS_FE_FN_CATALOGO('DIDEN', ISNULL(T1."U_BPP_TDC",'1'))),
"CONDUCTOR_DOCUMENTO_IDENTIDAD" = ISNULL(T1."U_BPP_DCON",'99999999'),
"CONDUCTOR_RAZON_SOCIAL" = ISNULL(T8."Name",'INTERNO'),
"CONDUCTOR_LICENCIA_CONDUCIR" = T1."U_BPP_MDFC",
"VEHICULO_MARCA" = T1."U_BPP_MDVN",
"VEHICULO_NUMERO_PLACA" = T1."U_BPP_MDVC",
"VEHICULO_CERTIFICADO_INSCRIPCION" = NULL
FROM OWTR T1
LEFT JOIN WTR1 T2 ON T1."DocEntry"=T2."DocEntry"
LEFT JOIN OITM T3 ON T2."ItemCode"=T3."ItemCode"
LEFT JOIN OCRD T5 ON T1."CardCode" = T5."CardCode"
LEFT JOIN WTR12 T6 ON T1."DocEntry"=T6."DocEntry"
LEFT JOIN CRD1 T7 ON T5."CardCode"=T7."CardCode"
LEFT JOIN "@BPP_CONDUC" T8 ON T1."U_BPP_MDFN"=T8."Code"
WHERE T1."DocEntry"= @DocEntry	AND  T1."ObjType"= @ObjType 

END