CREATE FUNCTION PLUS_FE_FN_CATALOGO(
	@TIPO   VARCHAR(5),
	@CODIGO VARCHAR(30)
)
RETURNS NVARCHAR(200)
AS
BEGIN
	DECLARE @VALOR VARCHAR(100) = ''

	IF @TIPO = 'DIDEN' BEGIN
		SET @VALOR = 
		CASE @CODIGO
			WHEN 0 THEN 'DOC_TRIB_NO_DOM_SIN_RUC'
			WHEN 1 THEN 'DOC_NACIONAL_DE_IDENTIDAD'
			WHEN 4 THEN 'CARNET_DE_EXTRANJERIA'
			WHEN 6 THEN 'RUC'
			WHEN 7 THEN 'PASAPORTE' 
			WHEN 8 THEN 'CED_DIPLOMATICA_IDENTIDAD'
		END
	END
	ELSE IF @TIPO = 'TOPER' BEGIN --Catálogo de Tipo Operación
		SET @VALOR = 
		CASE @CODIGO
			WHEN '0101' THEN 'VENTA_INTERNA'  --Para ventas nacionales, factura, boleta, anticipos, notas
			WHEN '0200' THEN 'EXPORTACION'    
		END
	END
	ELSE IF @TIPO = 'MOTNC' BEGIN --Catalogo Motivo Nota Crédito
		SET @VALOR = 
		CASE @CODIGO
			WHEN '01' THEN 'ANULACION_OPERACION'
			WHEN '02' THEN 'ANULACION_ERROR_RUC'
			WHEN '03' THEN 'CORRECCION_ERROR_DESCRIPCION'
			WHEN '04' THEN 'DESCUENTO_GLOBAL'
			WHEN '05' THEN 'DESCUENTO_POR_ITEM'
			WHEN '06' THEN 'DEVOLUCION_TOTAL'
			WHEN '07' THEN 'DEVOLUCION_POR_ITEM'
			WHEN '08' THEN 'BONIFICACION'
			WHEN '09' THEN 'DISMINUCION_DEL_VALOR'
			WHEN '10' THEN 'OTROS_CONCEPTOS'
		END
	END
	ELSE IF @TIPO = 'MOTND' BEGIN --Catalogo Motivo Nota Débito
		SET @VALOR = 
		CASE @CODIGO
			WHEN '01' THEN 'INTERES_POR_MORA'
			WHEN '02' THEN 'AUMENTO_EN_EL_VALOR'
			WHEN '03' THEN 'PENALIDADES_Y_OTROS'
		END
	END
	ELSE IF @TIPO = 'TDOCU' BEGIN --Catalogo Tipo Documento
		SET @VALOR = 
		CASE @CODIGO
			WHEN '01' THEN 'FACTURA'
			WHEN '03' THEN 'BOLETA'
			WHEN '07' THEN 'NOTACREDITO'
			WHEN '08' THEN 'NOTADEBITO'
		END
	END
	--ELSE IF @TIPO = 'FPAGO' BEGIN --Catalogo Medio de pago
		--SET @VALOR = 
		--CASE @CODIGO
			--WHEN 'Deposito Cuenta' THEN 'DEPOSITO_CUENTA'
			--WHEN 'Transferencia Bancaria' THEN 'TRANSFERENCIA_FONDOS'
			--WHEN 'Tarjeta de débito' THEN 'TARJETA_DEBITO'
			--WHEN 'Efectivo' THEN 'EFECTIVO'
			--WHEN 'Otros medio de pago' THEN 'OTROS_MEDIO_PAGO'
		--END
	--END
	ELSE IF @TIPO = 'TAFEC' BEGIN --Catálogo Tipo de Afectación
		SET @VALOR = 
		CASE @CODIGO
			WHEN 10 THEN 'GRAVADO_OPERACION_ONEROSA'
			WHEN 11 THEN 'GRAVADO_RETIRO_POR_PREMIO'
			WHEN 12 THEN 'GRAVADO_RETIRO_POR_DONACION'
			WHEN 13 THEN 'GRAVADO_RETIRO'
			WHEN 14 THEN 'GRAVADO_RETIRO_POR_PUBLICIDAD' 
			WHEN 15 THEN 'GRAVADO_BONIFICACIONES'
			WHEN 16 THEN 'GRAVADO_RETIRO_POR_ENTREGA_A_TRABAJADORES'
			WHEN 17 THEN 'GRAVADO_IVAP'
			WHEN 20 THEN 'EXONERADO_OPERACION_ONEROSA'
			WHEN 21 THEN 'EXONERADO_TRANSFERENCIA_GRATUITA'
			WHEN 30 THEN 'INAFECTO_OPERACION_ONEROSA'
			WHEN 31 THEN 'INAFECTO_RETIRO_POR_BONIFACION'
			WHEN 32 THEN 'INAFECTO_RETIRO'
			WHEN 33 THEN 'INAFECTO_RETIRO_POR_MUESTRAS_MEDICAS'
			WHEN 34 THEN 'INAFECTO_POR_CONVENIO_COLECTIVO'
			WHEN 35 THEN 'INAFECTO_RETIRO_POR_PREMIO'
			WHEN 36 THEN 'INAFECTO_RETIRO_POR_PUBLICIDAD'
			WHEN 40 THEN 'EXPORTACION'
		END
	END
	ELSE IF @TIPO = 'UNDME' BEGIN --Catalogo Unidades
		SET @VALOR = 
		CASE @CODIGO
			WHEN 'NIU' THEN 'UNIDAD_BIENES'
			WHEN 'ZZ'  THEN 'UNIDAD_SERVICIOS'
			WHEN 'DZP' THEN 'DOCENA'
			WHEN 'GLI' THEN 'GALON_INGLES'
			WHEN 'GLL' THEN 'US_GALON'
			ELSE (SELECT REPLACE("Name",' ','_') FROM "@INT_UNME" WHERE "Code"=@CODIGO)
		END
	END
	ELSE IF @TIPO = 'MOTTC' BEGIN --Catalogo Motivo Traslado Guía Remisión
		SET @VALOR = 
		CASE @CODIGO
			WHEN '01' THEN 'VENTA'
			WHEN '02' THEN 'COMPRA'
			WHEN '04' THEN 'TRASLADO_ESTABLECIMIENTOS'
			WHEN '08' THEN 'IMPORTACION'
			WHEN '09' THEN 'EXPORTACION'
			WHEN '13' THEN 'OTROS'
			WHEN '14' THEN 'VENTA_SUJETA_CONFIRMACION_COMPRADOR'
			WHEN '18' THEN 'TRASLADO_EMISOR_ITINERANTE'
			WHEN '19' THEN 'TRASLADO_ZONA_PRIMARIA'
		END
	END
	ELSE IF @TIPO = 'MOTTD' BEGIN --Catalogo Motivo Traslado Guía Remisión (Descripción)
		SET @VALOR = 
		CASE @CODIGO
			WHEN '01' THEN 'VENTA'
			WHEN '02' THEN 'COMPRA'
			WHEN '04' THEN 'TRASLADO ENTRE ESTABLECIMIENTOS DE LA MISMA EMPRESA'
			WHEN '08' THEN 'IMPORTACION'
			WHEN '09' THEN 'EXPORTACION'
			WHEN '13' THEN 'OTROS'
			WHEN '14' THEN 'VENTA SUJETA A CONFIRMACION DEL COMPRADOR'
			WHEN '18' THEN 'TRASLADO EMISOR ITINERANTE CP'
			WHEN '19' THEN 'TRASLADO A ZONA PRIMARIA'
		END
	END
	ELSE IF @TIPO = 'MODTR' BEGIN --Catalogo Modalidad Traslado
		SET @VALOR = 
		CASE @CODIGO
			WHEN '01' THEN 'PUBLICO'
			WHEN '02' THEN 'PRIVADO'
		END
	END
	ELSE IF @TIPO = 'TRPRO' BEGIN --Catalogo Trasbordo Programado
		SET @VALOR = 
		CASE @CODIGO
			WHEN '0' THEN 'False'
			WHEN '1' THEN 'True'
		END
	END
	ELSE IF @TIPO = 'FPAGO' BEGIN --Catalogo Forma Pago
		SET @CODIGO = CASE @CODIGO WHEN 'TARJETA DE CREDITO' THEN 'TRC'
								   WHEN 'TARJETA DE DEBITO'  THEN 'TRD'
								   ELSE @CODIGO
					  END
		SET @VALOR = 
		CASE LEFT(@CODIGO,3)
			WHEN '-'   THEN 'CONTADO' -- Contado
			WHEN 'CON' THEN 'CONTADO' -- Contado
			WHEN 'CRE' THEN 'CREDITO' -- Credito
			WHEN 'LET' THEN 'CREDITO' -- Letra
			WHEN 'TRC' THEN 'CREDITO' -- Tarjeta de credito
			WHEN 'TRD' THEN 'CONTADO' -- Tarjeta de debito
			WHEN 'COM' THEN 'CONTADO' -- Compensacion
			WHEN 'OBS' THEN 'CONTADO' -- Obsequio
			WHEN 'CAN' THEN 'CONTADO' -- Canje
			WHEN 'AUS' THEN 'CONTADO' -- Auspicio
		END
	END

	RETURN @VALOR
END