CREATE PROCEDURE IDC_FE_EXTRACCION_CABECERA
AS BEGIN

DECLARE @ML NVARCHAR(3);

SET @ML = (SELECT TOP 1  ISNULL(T0."MainCurncy",'')   FROM OADM T0);


SELECT TOP 5 *  FROM (
-- BEGIN FACTURAS - BOLETAS
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) END "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) END "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8) "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM INV1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) END "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO ELSE NULL END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDSO ELSE NULL END "FE_SERIE_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)  ELSE NULL END "FE_CORRELATIVO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_TIPOND ELSE NULL END "FE_CODIGO_MOTIVO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_MOTND ELSE NULL END "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
NULL  "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
UPPER(LEFT(ISNULL(T11.Street,'') + ' ' + ISNULL(T11.County,'') + ' ' + ISNULL(T11.City,'')+ ' ' + ISNULL(T12.Name,'')+ ' ' + ISNULL(T14.Name,''),500)) "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM INV1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0)))  
FROM OSTA TX1 INNER JOIN INV4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) end "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000'  "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM OINV T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN INV12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11.Country=T14.Code, 
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC') AND LEFT(T0.U_BPP_MDSD,1) IN ('F','B') AND T0.U_BPP_MDTD IN ('01','03','07','08')  AND T0."DocSubType"<>'DN' AND T0.CANCELED='N'
-- END FACTURAS - BOLETAS

UNION ALL

-- BEGIN NOTAS DE DÉBITO ("DocSubType"='DN')
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) END "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8)  "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM INV1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO ELSE NULL END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDSO ELSE NULL END "FE_SERIE_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)  ELSE NULL END "FE_CORRELATIVO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_TIPOND ELSE NULL END "FE_CODIGO_MOTIVO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_MOTND ELSE NULL END "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
CASE WHEN T0."DocSubType" = 'DN' THEN T14.DocDate ELSE NULL END "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
LEFT(ISNULL(LEFT(REPLACE(REPLACE(REPLACE(T0.Address,CHAR(10),' ') ,CHAR(13),' ') ,'  ',' '),500),ISNULL(T11.Street,'') + ' ' + ISNULL(T11.County,'') + ' ' + ISNULL(T11.City,'') + ' ' + ISNULL(T12.Name,'')),500) "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM INV1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0)))  
FROM OSTA TX1 INNER JOIN INV4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000' "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM OINV T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN INV12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
INNER JOIN OINV T14 ON T14."NumAtCard"= CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO+T0.U_BPP_MDSO+'-'+T0.U_BPP_MDCO ELSE T0.U_BPP_MDTD+'-'+T0.U_BPP_MDSD+'-'+T0.U_BPP_MDCD END, 
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC')  AND LEFT(T0.U_BPP_MDSD,1) IN ('F','B') AND T0.U_BPP_MDTD IN ('01','03','07','08') AND T0."DocSubType"='DN' AND T0.CANCELED='N'
-- END NOTAS DE DÉBITO ("DocSubType"='DN')

UNION ALL

-- BEGIN DOCUMENTO ANTICIPO
SELECT
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) END "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM DPI9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) END "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8)   "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM DPI1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) END "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO ELSE NULL END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDSO ELSE NULL END "FE_SERIE_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)  ELSE NULL END "FE_CORRELATIVO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_TIPOND ELSE NULL END "FE_CODIGO_MOTIVO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_MOTND ELSE NULL END "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
NULL "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
ISNULL(T11."Street",'') +' '+ ISNULL(T11."ZipCode",'') + ' '+ISNULL(T11."County",'') + ' '+ISNULL(T12."Name",'') "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM DPI1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0)))  
FROM OSTA TX1 INNER JOIN DPI4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN DPI1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From DPI3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from DPI4 C INNER JOIN DPI1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From DPI3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from DPI4 C INNER JOIN DPI1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From DPI3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) end "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000' "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM ODPI T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN DPI12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode",  
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC') AND LEFT(T0.U_BPP_MDSD,1) IN ('F','B') AND T0.U_BPP_MDTD IN ('01','03','07','08') AND T0.CANCELED='N'
-- END DOCUMENTO ANTICIPO

UNION ALL

-- BEGIN NOTA DE CRÉDITO
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) END "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM RIN9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8)  "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM RIN1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) END "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
T0.U_BPP_MDTO "FE_TIPO_DOCUMENTO_AFECTADO",
T0.U_BPP_MDSO "FE_SERIE_AFECTADO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)   "FE_CORRELATIVO_AFECTADO",
T0.U_IDC_TIPONC "FE_CODIGO_MOTIVO",
T0.U_IDC_MOTNC "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
CASE WHEN T14.DocEntry IS NOT NULL THEN  T14.DocDate WHEN T15.DocEntry IS NOT NULL THEN  T15.DocDate END "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
ISNULL(T11."Street",'') +' '+ ISNULL(T11."ZipCode",'') + ' '+ISNULL(T11."County",'') + ' '+ISNULL(T12."Name",'') "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM RIN1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,2)))  
FROM OSTA TX1 INNER JOIN RIN4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from RIN4 C INNER JOIN RIN1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From RIN3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from RIN4 C INNER JOIN RIN1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From RIN3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from RIN4 C INNER JOIN RIN1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From RIN3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000' "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM ORIN T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN RIN12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OINV T14 ON T14."NumAtCard"=T0.U_BPP_MDTO+T0.U_BPP_MDSO+'-'+T0.U_BPP_MDCO
LEFT JOIN ODPI T15 ON T15."NumAtCard"=T0.U_BPP_MDTO+T0.U_BPP_MDSO+'-'+T0.U_BPP_MDCO,  
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC') AND LEFT(T0.U_BPP_MDSD,1) IN ('F','B') AND T0.U_BPP_MDTD IN ('07')  AND T0.CANCELED='N'
-- END NOTA DE CRÉDITO

/*********************************************************CONTINGENCIA*************************************************/
UNION ALL

-- BEGIN DOCUMENTO DE CONTINGENCIA GENERAL
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) END "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) END "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8) "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM INV1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) END "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO ELSE NULL END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDSO ELSE NULL END "FE_SERIE_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)  ELSE NULL END "FE_CORRELATIVO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_TIPOND ELSE NULL END "FE_CODIGO_MOTIVO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_MOTND ELSE NULL END "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
NULL  "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
UPPER(LEFT(ISNULL(T11.Street,'') + ' ' + ISNULL(T11.County,'') + ' ' + ISNULL(T11.City,'')+ ' ' + ISNULL(T12.Name,'')+ ' ' + ISNULL(T14.Name,''),500)) "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM INV1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0)))  
FROM OSTA TX1 INNER JOIN INV4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE  ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) end "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000'  "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM OINV T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN INV12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11.Country=T14.Code, 
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC')  AND T0.U_BPP_MDTD IN ('01','03','07','08') AND T0.U_IDC_ESCONTINGENCIA='Y' AND T0.CANCELED='N'
-- END DOCUMENTO DE CONTINGENCIA GENERAL

UNION ALL

-- BEGIN DOCUMENTO DE CONTINGENCIA REFERENCIADA A OTRO DOCUMENTO (INNER JOIN OINV T14)
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM INV9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) END "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8)  "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM INV1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO ELSE NULL END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDSO ELSE NULL END "FE_SERIE_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)  ELSE NULL END "FE_CORRELATIVO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_TIPOND ELSE NULL END "FE_CODIGO_MOTIVO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_MOTND ELSE NULL END "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
CASE WHEN T0."DocSubType" = 'DN' THEN T14.DocDate ELSE NULL END "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
LEFT(ISNULL(LEFT(REPLACE(REPLACE(REPLACE(T0.Address,CHAR(10),' ') ,CHAR(13),' ') ,'  ',' '),500),ISNULL(T11.Street,'') + ' ' + ISNULL(T11.County,'') + ' ' + ISNULL(T11.City,'') + ' ' + ISNULL(T12.Name,'')),500) "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM INV1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0)))  
FROM OSTA TX1 INNER JOIN INV4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from INV4 C INNER JOIN INV1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From INV1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From INV3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000' "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM OINV T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN INV12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
INNER JOIN OINV T14 ON T14."NumAtCard"= CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO+T0.U_BPP_MDSO+'-'+T0.U_BPP_MDCO ELSE T0.U_BPP_MDTD+'-'+T0.U_BPP_MDSD+'-'+T0.U_BPP_MDCD END, 
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC')  AND T0.U_BPP_MDTD IN ('01','03','07','08') AND T0.U_IDC_ESCONTINGENCIA='Y' AND T0.CANCELED='N'
-- END DOCUMENTO DE CONTINGENCIA REFERENCIADA A OTRO DOCUMENTO (INNER JOIN OINV T14)

UNION ALL

-- BEGIN ANTICIPO DE CONTINGENCIA
SELECT
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) END "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM DPI9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) END "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8)   "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM DPI1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) END "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDTO ELSE NULL END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_BPP_MDSO ELSE NULL END "FE_SERIE_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)  ELSE NULL END "FE_CORRELATIVO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_TIPOND ELSE NULL END "FE_CODIGO_MOTIVO",
CASE WHEN T0."DocSubType" = 'DN' THEN T0.U_IDC_MOTND ELSE NULL END "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
NULL "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
ISNULL(T11."Street",'') +' '+ ISNULL(T11."ZipCode",'') + ' '+ISNULL(T11."County",'') + ' '+ISNULL(T12."Name",'') "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM DPI1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,0)))  
FROM OSTA TX1 INNER JOIN DPI4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from DPI4 C INNER JOIN DPI1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From DPI3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from DPI4 C INNER JOIN DPI1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From DPI3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from DPI4 C INNER JOIN DPI1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From DPI1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From DPI3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000' "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM ODPI T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN DPI12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode",  
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC')  AND T0.U_BPP_MDTD IN ('01','03','07','08') AND T0.U_IDC_ESCONTINGENCIA='Y' AND T0.CANCELED='N'
-- END ANTICIPO DE CONTINGENCIA

UNION ALL

-- BEGIN NOTA DE CRÉDITO DE CONTINGENCIA
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal" - T0."VatSum" + T0."DiscSum"  ELSE T0."DocTotalFC" - T0."VatSumFC"  + T0."DiscSumFC" END,0) END "FE_IMPORTEVENTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE (SELECT Case T0."DocCur" WHEN @ML THEN SUM(T6."DrawnSum") ELSE SUM(T6."DrawnSumFc") END FROM RIN9 T6 where T6."DocEntry"=T0."DocEntry") END "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."DocTotal"   ELSE T0."DocTotalFC" END,0) "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8)  "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
(SELECT COUNT(1) FROM RIN1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE T0."DocCur" WHEN @ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END,0.00) END "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
T0.U_BPP_MDTO "FE_TIPO_DOCUMENTO_AFECTADO",
T0.U_BPP_MDSO "FE_SERIE_AFECTADO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCO)),8)   "FE_CORRELATIVO_AFECTADO",
T0.U_IDC_TIPONC "FE_CODIGO_MOTIVO",
T0.U_IDC_MOTNC "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
CASE WHEN T0."LangCode" = 3 THEN ISNULL(T10."Trans",ISNULL(T6."PymntGroup",'')) ELSE ISNULL(T6."PymntGroup",'') END "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
T14.DocDate "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
ISNULL(T11."Street",'') +' '+ ISNULL(T11."ZipCode",'') + ' '+ISNULL(T11."County",'') + ' '+ISNULL(T12."Name",'') "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
CASE WHEN T0."LangCode" = 3 THEN T2."FrgnName" ELSE T2."CurrName" END "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
NULL "FE_TIPO_GUIA_REMISION",
T0."DocType" "FE_TIPO_DOCUMENTO_SER_ART",
ISNULL(T0.U_IDC_TIPFAC,'') "FE_TIPO_OPERACION",
(SELECT TOP 1 CONCAT(TT1.Street,' ',TT1.StreetNo,' ',TT1.Block,' ',TT1.City) FROM RIN1 TT0 INNER JOIN OWHS TT1 ON TT0.WhsCode=TT1.WhsCode WHERE TT0.DocEntry=T0.DocEntry AND TT0.ObjType=T0.ObjType)"FE_CU01",
T0.DocNum "FE_CU02",
REPLACE(REPLACE(CAST(T0.U_IDC_COM_EXPO AS NVARCHAR(MAX)),CHAR(10),' '),CHAR(13),' ')  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL(CASE WHEN T0."DocCur" = @ML THEN T0."VatSum" ELSE T0."VatSumFC" END,0.00) END "FE_IMPUESTO_TOTAL",
ISNULL((SELECT MAX(CAST(TX1."Rate" AS DECIMAL(19,2)))  
FROM OSTA TX1 INNER JOIN RIN4 TX2 ON TX1."Code"=TX2."StaCode" 
WHERE TX2."DocEntry"=T0."DocEntry"  GROUP BY TX2."DocEntry" ),0.00)	"FE_PORCENTAJE_IMPUESTO",
ISNULL(T0.DiscPrcnt,0.00) "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (SELECT Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from RIN4 C INNER JOIN RIN1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		WHERE C.DocEntry= T0.DocEntry and C.TaxSum<>0  AND C.RelateType IN (1,2,3) 
			and ISNULL(( select TaxOnly From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'')='A'
			or   ISNULL( ( select U_BPP_OPER From RIN3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'') ='A')
		GROUP by C.LineNum,C.RelateType) BB ),0.00) END "FE_OPE_GRAVADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
	from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
			from RIN4 C INNER JOIN RIN1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
			where C.DocEntry= T0.DocEntry 
				and C.TaxSum=0  
				and isnull(( select TaxOnly From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
				and (ISNULL( ( select U_BPP_OPER From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='I'
				or   ISNULL( ( select U_BPP_OPER From RIN3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='I')
				AND C.RelateType IN (1,2,3)
			GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_INAFECTA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN 0.00 ELSE ISNULL((select sum(BB.BaseSum) 
from (	select Case T0.DocCur WHEN @ML THEN max(C.BaseSum) ELSE max(C.BaseSumFrg) END as BaseSum 
		from RIN4 C INNER JOIN RIN1 D ON C.DocEntry = D.DocEntry AND C.LineNum = D.LineNum 
		where C.DocEntry= T0.DocEntry 
			and C.TaxSum=0  
			and isnull(( select TaxOnly From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ),'N')='N' 
			and (ISNULL( ( select U_BPP_OPER From RIN1 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A')='E'
			or   ISNULL( ( select U_BPP_OPER From RIN3 where DocEntry=C.DocEntry and LineNum=C.LineNum ) ,'A') ='E')
			AND C.RelateType IN (1,2,3)
		GROUP by C.LineNum,C.RelateType) BB),0.00) END "FE_OPE_EXONERADA",
CASE WHEN ISNULL(T0.U_IDC_TIPVTA,'01')='03' THEN CASE T0."DocCur" WHEN @ML THEN T0.DocTotal - T0.VatSum ELSE T0.DocTotalFC - T0.VatSumFC END ELSE  0.00 END "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000' "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM ORIN T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN RIN12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
INNER JOIN OINV T14 ON T14."NumAtCard"=T0.U_BPP_MDTO+T0.U_BPP_MDSO+'-'+T0.U_BPP_MDCO ,  
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC')  AND T0.U_BPP_MDTD IN ('01','03','07','08') AND T0.U_IDC_ESCONTINGENCIA='Y' AND T0.CANCELED='N'
-- END NOTA DE CRÉDITO DE CONTINGENCIA

UNION ALL

-- BEGIN GUIA DE REMISION
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
0.00 "FE_IMPORTEVENTA",
0.00 "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
0.00 "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8) "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
0 "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
0.00 "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
NULL "FE_TIPO_DOCUMENTO_AFECTADO",
NULL "FE_SERIE_AFECTADO",
NULL "FE_CORRELATIVO_AFECTADO",
NULL "FE_CODIGO_MOTIVO",
NULL "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
NULL "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
NULL  "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
UPPER(LEFT(ISNULL(T11.Street,'') + ' ' + ISNULL(T11.County,'') + ' ' + ISNULL(T11.City,'')+ ' ' + ISNULL(T12.Name,'')+ ' ' + ISNULL(T14.Name,''),500)) "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
NULL "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
'09' "FE_TIPO_GUIA_REMISION",
NULL "FE_TIPO_DOCUMENTO_SER_ART",
NULL "FE_TIPO_OPERACION",
NULL"FE_CU01",
T0.DocNum "FE_CU02",
NULL  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
0.00"FE_IMPUESTO_TOTAL",
0.00 "FE_PORCENTAJE_IMPUESTO",
0.00 "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
0.00 "FE_OPE_GRAVADA",
0.00 "FE_OPE_INAFECTA",
0.00 "FE_OPE_EXONERADA",
0.00 "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000'  "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM ODLN T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN DLN12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11.Country=T14.Code, 
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC') AND LEFT(T0.U_BPP_MDSD,1) IN ('T') AND T0.U_BPP_MDTD IN ('09')  AND T0.CANCELED='N'
-- END GUIA DE REMISION


UNION ALL

--BEGIN GUIA DE REMISIÓN DESDE TRANSFERENCIA DE STOCK
SELECT 
T0.U_BPP_MDTD+T0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_ID",
0.00 "FE_IMPORTEVENTA",
0.00 "FE_IMPORTEANTICIPOS",
0.00 "FE_IMPORTEOTROSCARGOS",
0.00 "FE_TOTALPRECIOVENTA",
RIGHT('00000000' + Ltrim(Rtrim(T0."U_BPP_MDCD")),8) "FE_CORRELATIVODOCUMENTO",
T0."DocDate" "FE_FECHAEMISION",
T0."DocDueDate" "FE_FECHAVENCIMIENTO",
T2."ISOCurrCod" "FE_CODIGOMONEDA",
0 "FE_CANTIDADITEM",
T0.U_IDC_OC "FE_ORDENCOMPRA",
T20."PrintHeadr" "FE_NOMBRECOMERCIAL_EMISOR",
T20."PrintHeadr" "FE_RAZONSOCIAL_EMISOR",
T20."TaxIdNum" "FE_DOCUMENTOIDENTIDAD_EMISOR",
'6' "FE_TIPODOCUMENTOIDENTIDAD_EMISOR",
T1."CardName" "FE_NOMBRECOMERCIAL_ADQUIRIENTE",
T1."CardName" "FE_RAZONSOCIAL_ADQUIRIENTE",
LEFT(T1."LicTradNum",11) "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTOIDENTIDAD_ADQUIRIENTE",
'' "FE_CUENTABANCO_DETRACCION",
0.00 "FE_PORCENTAJE_DETRACCION",
0.00 "FE_MONTO_DETRACCION",
0.00 "FE_DESCUENTOGLOBAL",
T0.U_BPP_MDTD "FE_TIPODOCUMENTO",
T0.U_BPP_MDSD "FE_SERIEDOCUMENTO",
NULL "FE_TIPO_DOCUMENTO_AFECTADO",
NULL "FE_SERIE_AFECTADO",
NULL "FE_CORRELATIVO_AFECTADO",
NULL "FE_CODIGO_MOTIVO",
NULL "FE_DESCRIPCION_MOTIVO",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
T0.U_IDC_FESTADO "FE_ESTADO",
T20."Phone1" "FE_TELEFONO",
T20."Phone2" "FE_FAX",
T21."IntrntAdrs" "FE_PAGINA_WEB",
NULL "FE_CONDICION_PAGO",
ISNULL(T20."E_Mail",'facturacion.peru@winnerssport.com') "FE_EMISOR_CORREO_ELECTRONICO",
ISNULL(T1."E_Mail",'facturacion.peru@winnerssport.com') "FE_ADQUIRIENTE_CORREO_ELECTRONICO",
NULL  "FE_FECHA_EMISION_DOCUMENTO_AFECTADO",
LEFT(ISNULL(UPPER(CONCAT (T21."Street" , ' ',T21."StreetNo",' ',T21.City, ' ',T21.County, ' ',T22.Name)),''),500) "FE_DIRECCION_EMISOR",
UPPER(LEFT(ISNULL(T11.Street,'') + ' ' + ISNULL(T11.County,'') + ' ' + ISNULL(T11.City,'')+ ' ' + ISNULL(T12.Name,'')+ ' ' + ISNULL(T14.Name,''),500)) "FE_DIRECCION_ADQUIRIENTE",
ISNULL(T3."GlbLocNumB",'') "FE_UBIGEO_ADQUIRIENTE",
ISNULL(T21."GlblLocNum",'') "FE_UBIGEO_EMISOR",
LEFT(ISNULL(UPPER(T21."Street"),''),500) "FE_CALLE_EMISOR",
LEFT(UPPER(ISNULL(T3."StreetB",ISNULL(T11."Street",''))),100) "FE_CALLE_ADQUIRIENTE",
ISNULL(LEFT(ISNULL(T21."Block",''),30),'') "FE_URBANIZACION_EMISOR",
LEFT(ISNULL(T3."BlockB",ISNULL(T11."Block",'')),30) "FE_URBANIZACION_ADQUIRIENTE",
ISNULL(UPPER(T20."Country"),'') "FE_PAIS_EMISOR",
LEFT(ISNULL(T3."CountryB",T11."Country"),2) "FE_PAIS_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T22."Name",'')),'') "FE_DEPARTAMENTO_EMISOR",
LEFT(UPPER(ISNULL(T4."Name",ISNULL(T12."Name",''))),100) "FE_DEPARTAMENTO_ADQUIRIENTE",
LEFT(UPPER(ISNULL(T3."CityB",ISNULL(T11."City",''))),100) "FE_PROVINCIA_ADQUIRIENTE",
ISNULL(UPPER(ISNULL(T21."City",'')),'') "FE_PROVINCIA_EMISOR",
ISNULL(UPPER(T21."County"),'') "FE_DISTRITO_EMISOR",
LEFT(UPPER(ISNULL(T3."CountyB",ISNULL(T11."County",''))),100) "FE_DISTRITO_ADQUIRIENTE",
NULL "FE_NOMBRE_MONEDA",
NULL "FE_COD_REGIMEN_RETENCION",
0.00 "FE_TASA_RETENCION",
0.00 "FE_IMPORTE_TOTAL_PAGADO",
0.00 "FE_IMPORTE_TOTAL_RETENIDO",
'09' "FE_TIPO_GUIA_REMISION",
NULL "FE_TIPO_DOCUMENTO_SER_ART",
NULL "FE_TIPO_OPERACION",
NULL"FE_CU01",
T0.DocNum "FE_CU02",
NULL  "FE_CU03",
NULL "FE_CU04",
NULL "FE_CU05",
NULL "FE_CU06",
NULL "FE_CU07",
NULL "FE_CU08",
NULL "FE_CU09",
NULL "FE_CU10",
NULL "FE_CU11",
NULL "FE_CU12",
NULL "FE_CU13",
NULL "FE_CU14",
NULL "FE_CU15",
NULL "FE_CU16",
NULL "FE_CU17",
NULL "FE_CU18",
NULL "FE_CU19",
NULL "FE_CU20",
NULL "FE_RUTA_PDF",
NULL "FE_RUTA_CDR",
NULL "FE_RUTA_XML",
0.00"FE_IMPUESTO_TOTAL",
0.00 "FE_PORCENTAJE_IMPUESTO",
0.00 "FE_PORCENTAJE_DESCUENTO",
T0."Comments" "FE_COMENTARIOS",
0.00 "FE_OPE_GRAVADA",
0.00 "FE_OPE_INAFECTA",
0.00 "FE_OPE_EXONERADA",
0.00 "FE_OPE_GRATUITA",
T2."ChkName" "FE_SIMBOLO_MONEDA",
'0000'  "FE_COD_EMI_DIRECCION",
'0000' "FE_COD_ADQ_DIRECCION",
'' "FE_TIPO_DETRACCION",
'ESTANDAR' "FE_FORMATOPDF",
'' "FE_COD_MEDPAGO"
FROM OWTR T0
INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"
INNER JOIN OCRN T2 ON T2."CurrCode" = T0."DocCur"
LEFT JOIN WTR12 T3 ON T3."DocEntry" = T0."DocEntry"
LEFT JOIN OCST T4 ON T3."StateB" = T4."Code" AND T3."CountryB" = T4."Country"
LEFT JOIN OSLP T5 ON T5."SlpCode" = T0."SlpCode"
LEFT JOIN OCTG T6 ON T0."GroupNum" = T6."GroupNum"
LEFT JOIN OMLT T7 ON T1."CardCode" = T7."PK"
LEFT JOIN MLT1 T8 ON T7."TranEntry" = T8."TranEntry"
LEFT JOIN OMLT T9 ON CAST(T0."GroupNum" AS nvarchar(254)) = T9."PK"
LEFT JOIN MLT1 T10 ON T9."TranEntry" = T10."TranEntry"
LEFT JOIN CRD1 T11 ON T11."Address" = T1."BillToDef" AND T11."AdresType" = 'B' AND T11."CardCode" = T1."CardCode"
LEFT JOIN OCST T12 ON T11."State" = T12."Code" AND T11."Country" = T12."Country"
LEFT JOIN OSLP T13 ON T13."SlpCode"=T0."SlpCode"
LEFT JOIN OCRY T14 ON T11.Country=T14.Code, 
OADM  T20 
LEFT JOIN ADM1 T21 ON T20."Code"=T21."Code"
LEFT JOIN OCST T22 ON T21."State" = T22."Code" AND T20."Country"=T22."Country"
WHERE T0.U_IDC_FESTADO IN('PE','DC') AND LEFT(T0.U_BPP_MDSD,1) IN ('T') AND T0.U_BPP_MDTD IN ('09')  AND T0.CANCELED='N'
--END GUIA DE REMISIÓN DESDE TRANSFERENCIA DE STOCK


) T

END