CREATE PROCEDURE IDC_FE_EXTRACCION_LEYENDA
(@ObjType varchar(15), @DocEntry int )
AS BEGIN

DECLARE @ML nvarchar(3);
	
SELECT TOP 1 @ML = T0."MainCurncy" 
FROM OADM T0 INNER JOIN ADM1 T1 ON T0."Code" = T1."Code";

SELECT * FROM (

SELECT
TX0.U_BPP_MDTD+TX0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(TX0.U_BPP_MDCD)),8) "FE_ID",
'1000' "FE_CODIGOLEYENDA",
CASE 
WHEN (SELECT count(T0."LineNum") FROM "INV1" T0 WHERE T0."U_IDC_TAFE" IN ('10','20','30','40') AND T0."DocEntry" = @DocEntry AND T0."ObjType" = @ObjType) > 0 THEN [dbo].[IDC_FE_IMPORTE_TEXTO](TX0.DocCur,CONVERT(numeric(19,6),ROUND(CASE TX0.DocCur WHEN @ML THEN TX0.DocTotal ELSE TX0.DocTotalFC END,2)))
WHEN (SELECT count(T0."LineNum") FROM "INV1" T0 WHERE T0."U_IDC_TAFE" IN ('10','20','30','40') AND T0."DocEntry" = @DocEntry AND T0."ObjType" = @ObjType) = 0 THEN [dbo].[IDC_FE_IMPORTE_TEXTO](TX0.DocCur,0)
END  "FE_NOMBRELEYENDA"
FROM OINV TX0 WHERE Tx0."DocEntry" = @DocEntry AND Tx0."ObjType" = @ObjType

UNION ALL

SELECT
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN TX0.U_BPP_MDTD+TX0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(TX0.U_BPP_MDCD)),8) END "FE_ID",
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN '1002' END "FE_CODIGOLEYENDA",
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN  '"TRANSFERENCIA GRATUITA DE UN BIEN Y/O SERVICIO PRESTADO GRATUITAMENTE"' 
END  "FE_NOMBRELEYENDA"
FROM OINV TX0 WHERE Tx0."DocEntry" = @DocEntry AND Tx0."ObjType" = @ObjType

UNION ALL


SELECT
TX0.U_BPP_MDTD+TX0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(TX0.U_BPP_MDCD)),8) "FE_ID",
'1000' "FE_CODIGOLEYENDA",
CASE 
WHEN (SELECT count(T0."LineNum") FROM "RIN1" T0 WHERE T0."U_IDC_TAFE" IN ('10','20','30','40') AND T0."DocEntry" = @DocEntry AND T0."ObjType" = @ObjType) > 0 THEN [dbo].[IDC_FE_IMPORTE_TEXTO](TX0.DocCur,CONVERT(numeric(19,6),ROUND(CASE TX0.DocCur WHEN @ML THEN TX0.DocTotal ELSE TX0.DocTotalFC END,2)))
WHEN (SELECT count(T0."LineNum") FROM "RIN1" T0 WHERE T0."U_IDC_TAFE" IN ('10','20','30','40') AND T0."DocEntry" = @DocEntry AND T0."ObjType" = @ObjType) = 0 THEN [dbo].[IDC_FE_IMPORTE_TEXTO](TX0.DocCur,0)
END  "FE_NOMBRELEYENDA"
FROM ORIN TX0 WHERE Tx0."DocEntry" = @DocEntry AND Tx0."ObjType" = @ObjType

UNION ALL

SELECT
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN TX0.U_BPP_MDTD+TX0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(TX0.U_BPP_MDCD)),8) END "FE_ID",
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN '1002' END "FE_CODIGOLEYENDA",
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN  '"TRANSFERENCIA GRATUITA DE UN BIEN Y/O SERVICIO PRESTADO GRATUITAMENTE"' 
END  "FE_NOMBRELEYENDA"
FROM ORIN TX0 WHERE Tx0."DocEntry" = @DocEntry AND Tx0."ObjType" = @ObjType

UNION ALL

SELECT
TX0.U_BPP_MDTD+TX0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(TX0.U_BPP_MDCD)),8) "FE_ID",
'1000' "FE_CODIGOLEYENDA",
CASE 
WHEN (SELECT count(T0."LineNum") FROM "DPI1" T0 WHERE T0."U_IDC_TAFE" IN ('10','20','30','40') AND T0."DocEntry" = @DocEntry AND T0."ObjType" = @ObjType) > 0 THEN [dbo].[IDC_FE_IMPORTE_TEXTO](TX0.DocCur,CONVERT(numeric(19,6),ROUND(CASE TX0.DocCur WHEN @ML THEN TX0.DocTotal ELSE TX0.DocTotalFC END,2)))
WHEN (SELECT count(T0."LineNum") FROM "DPI1" T0 WHERE T0."U_IDC_TAFE" IN ('10','20','30','40') AND T0."DocEntry" = @DocEntry AND T0."ObjType" = @ObjType) = 0 THEN [dbo].[IDC_FE_IMPORTE_TEXTO](TX0.DocCur,0)
END  "FE_NOMBRELEYENDA"
FROM ODPI TX0 WHERE Tx0."DocEntry" = @DocEntry AND Tx0."ObjType" = @ObjType

UNION ALL

SELECT
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN TX0.U_BPP_MDTD+TX0.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(TX0.U_BPP_MDCD)),8) END "FE_ID",
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN '1002' END "FE_CODIGOLEYENDA",
CASE WHEN ISNULL(TX0.U_IDC_TIPVTA,'01')='03' THEN  '"TRANSFERENCIA GRATUITA DE UN BIEN Y/O SERVICIO PRESTADO GRATUITAMENTE"' 
END  "FE_NOMBRELEYENDA"
FROM ODPI TX0 WHERE Tx0."DocEntry" = @DocEntry AND Tx0."ObjType" = @ObjType ) T WHERE T.FE_CODIGOLEYENDA IS NOT NULL
;




END