CREATE PROCEDURE IDC_FE_EXTRACCION_RESUMEN_DIARIO_DETALLE (@Fecha NVARCHAR(50))
AS BEGIN

DECLARE @ML nvarchar(3);
		
SELECT TOP 1 @ML = T0."MainCurncy"
FROM OADM T0 INNER JOIN ADM1 T1 ON T0."Code" = T1."Code";


SELECT DISTINCT TA."FE_ID",
TA."FE_LINEA_ID",
TA."FE_TIPO_DOCUMENTO",
TA."FE_SERIE_DOCUMENTO",
TA."FE_CORRELATIVO_DOCUMENTO",
TA."FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
TA."FE_TIPODOCUMENTO_ADQUIRIENTE",
TA."FE_TOTAL_GRAVADAS",
TA."FE_TOTAL_EXONERADAS",
TA."FE_TOTAL_INAFECTAS",
TA."FE_TOTAL_GRATUITAS",
TA."FE_TOTAL_OTROS_CARGOS",
TA."FE_TOTAL_DESCUENTOS",
TA."FE_TOTAL_IGV",
TA."FE_TOTAL_ISC",
TA."FE_TOTAL_OTROS_TRIBUTOS",
TA."FE_IMPORTE_TOTAL",
TA."FE_CODIGO_MONEDA",
TA."FE_DOCENTRY",
TA."FE_OBJTYPE",
TA."FE_ESTADO",
TA."FE_TIPO_DOCUMENTO_AFECTADO",
TA."FE_SERIE_DOCUMENTO_AFECTADO",
TA."FE_CORRELATIVO_DOCUMENTO_AFECTADO"


 FROM (
/************************************************************* DOCUMENTOS EMITIDOS  *************************************************************/

SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(CASE WHEN T0.CANCELED='Y' THEN T4.U_BPP_NROLEGFT ELSE T0.U_BPP_MDCD END)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM INV4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN INV1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.U_IDC_FESTADO  IN ('RP') THEN  '1' WHEN T0.U_IDC_FESTADO  IN ('BP') THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM OINV T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
LEFT JOIN [@BPP_LPET] T4 ON T4.U_BPP_DOCENTRYFT=T0.DocEntry
WHERE T0."DocDate"= CONVERT(date, @Fecha) AND LEFT(T0.U_BPP_MDSD,1)='B'  AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP','RP')


UNION ALL


SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry"  AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM DPI4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN DPI1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='N' THEN '1' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ODPI T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
WHERE T0."DocDate"= CONVERT(date, @Fecha)  AND LEFT(T0.U_BPP_MDSD,1)='B'  AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP','RP')


UNION ALL


SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM RIN4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN RIN1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.U_IDC_FESTADO  IN ('RP') THEN  '1' WHEN T0.U_IDC_FESTADO  IN ('BP') THEN '3' END "FE_ESTADO",
ISNULL(T0.U_BPP_MDTO,'') "FE_TIPO_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDSO,'') "FE_SERIE_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDCO,'') "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ORIN T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
WHERE T0."DocDate"= CONVERT(date, @Fecha)  AND LEFT(T0.U_BPP_MDSD,1)='B'  AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP','RP')

UNION ALL
/*************************************************************************** CONTINGENCIA ***********************************************************************************/

SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM INV4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN INV1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.U_IDC_FESTADO  IN ('RP') THEN  '1' WHEN T0.U_IDC_FESTADO  IN ('BP') THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM OINV T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
WHERE T0."DocDate"= CONVERT(date, @Fecha)  AND T0.U_IDC_ESCONTINGENCIA='Y'  AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP','RP')

UNION ALL


SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry"  AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM DPI4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN DPI1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='N' THEN '1' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ODPI T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
WHERE T0."DocDate"= CONVERT(date, @Fecha)  AND T0.U_IDC_ESCONTINGENCIA='Y'  AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP','RP')

UNION ALL


SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM RIN4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN RIN1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.U_IDC_FESTADO  IN ('RP') THEN  '1' WHEN T0.U_IDC_FESTADO  IN ('BP') THEN '3' END "FE_ESTADO",
ISNULL(T0.U_BPP_MDTO,'') "FE_TIPO_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDSO,'') "FE_SERIE_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDCO,'') "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ORIN T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
WHERE T0."DocDate"= CONVERT(date, @Fecha)  AND T0.U_IDC_ESCONTINGENCIA='Y'  AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP','RP')


/*************************************************************  DOCUMENTOS CANCELADOS  *************************************************************/

/*
UNION ALL

SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(CASE WHEN T0.CANCELED='C' THEN T6.U_BPP_NROLEGFT ELSE T0.U_BPP_MDCD END)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM INV4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN INV1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='C' THEN '3' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM OINV T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
INNER JOIN INV1 T4 ON T0.DocEntry=T4.DocEntry
INNER JOIN OINV T5 ON T4.BaseEntry=T5.DocEntry
INNER JOIN "@BPP_LPET" T6 ON T5.DocEntry=T6.U_BPP_DOCENTRYFT AND T5.U_BPV_SERI=T6.U_BPP_SERIEFT
WHERE T0."DocDate"= CONVERT(date, @Fecha) AND LEFT(T0.U_BPP_MDSD,1)='B' AND T0.CANCELED IN ('C') AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP')


UNION ALL


SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(CASE WHEN T0.CANCELED='C' THEN T6.U_BPP_NROLEGFT ELSE T0.U_BPP_MDCD END)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry"  AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM DPI4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN DPI1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='C' THEN '3' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ODPI T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
INNER JOIN INV1 T4 ON T0.DocEntry=T4.DocEntry
INNER JOIN OINV T5 ON T4.BaseEntry=T5.DocEntry
INNER JOIN "@BPP_LPET" T6 ON T5.DocEntry=T6.U_BPP_DOCENTRYFT AND T5.U_BPV_SERI=T6.U_BPP_SERIEFT
WHERE T0."DocDate"= CONVERT(date, @Fecha) AND LEFT(T0.U_BPP_MDSD,1)='B' AND T0.CANCELED IN ('C') AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP')


UNION ALL


SELECT
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(CASE WHEN T0.CANCELED='C' THEN T6.U_BPP_NROLEGNC ELSE T0.U_BPP_MDCD END)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM RIN4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN RIN1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='C' THEN '3' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
ISNULL(T0.U_BPP_MDTO,'') "FE_TIPO_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDSO,'') "FE_SERIE_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDCO,'') "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ORIN T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
INNER JOIN RIN1 T4 ON T0.DocEntry=T4.DocEntry
INNER JOIN ORIN T5 ON T4.BaseEntry=T5.DocEntry
INNER JOIN "@BPP_LPET" T6 ON T5.DocEntry=T6.U_BPP_DOCENTRYNC AND T5.U_BPV_SERI=T6.U_BPP_SERIENC
WHERE T0."DocDate"= CONVERT(date, @Fecha) AND LEFT(T0.U_BPP_MDSD,1)='B' AND T0.CANCELED IN ('C') AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP')

UNION ALL

*/
/*************************************************************************** CONTINGENCIA ***********************************************************************************/
/*
SELECT 
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(CASE WHEN T0.CANCELED='C' THEN T6.U_BPP_NROLEGFT ELSE T0.U_BPP_MDCD END)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM INV4 C INNER JOIN INV1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM INV4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN INV1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='C' THEN '3' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM OINV T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
INNER JOIN INV1 T4 ON T0.DocEntry=T4.DocEntry
INNER JOIN OINV T5 ON T4.BaseEntry=T5.DocEntry
INNER JOIN "@BPP_LPET" T6 ON T5.DocEntry=T6.U_BPP_DOCENTRYFT AND T0.U_BPV_SERI=T6.U_BPP_SERIEFT
WHERE T0."DocDate"= CONVERT(date, @Fecha) AND LEFT(T0.U_BPP_MDSD,1)='B' AND T0.CANCELED IN ('C') AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP')


UNION ALL


SELECT 
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(CASE WHEN T0.CANCELED='C' THEN T6.U_BPP_NROLEGNC ELSE T0.U_BPP_MDCD END)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM DPI4 C INNER JOIN DPI1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry"  AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM DPI4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN DPI1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='N' THEN '1' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDTO,'') ELSE '' END "FE_TIPO_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDSO,'') ELSE '' END "FE_SERIE_DOCUMENTO_AFECTADO",
CASE WHEN T0."DocSubType" = 'DN' THEN ISNULL(T0.U_BPP_MDCO,'') ELSE '' END "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ODPI T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
INNER JOIN DPI1 T4 ON T0.DocEntry=T4.DocEntry
INNER JOIN ODPI T5 ON T4.BaseEntry=T5.DocEntry
INNER JOIN "@BPP_LPET" T6 ON T5.DocEntry=T6.U_BPP_DOCENTRYFT AND T5.U_BPV_SERI=T6.U_BPP_SERIEFT
WHERE T0."DocDate"= CONVERT(date, @Fecha) AND LEFT(T0.U_BPP_MDSD,1)='B' AND T0.CANCELED IN ('C') AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP')

UNION ALL


SELECT 
'' "FE_ID",
'' "FE_LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(CASE WHEN T0.CANCELED='C' THEN T6.U_BPP_NROLEGNC ELSE T0.U_BPP_MDCD END)),8) "FE_CORRELATIVO_DOCUMENTO",
T0."LicTradNum" "FE_DOCUMENTOIDENTIDAD_ADQUIRIENTE",
T1.U_BPP_BPTD "FE_TIPODOCUMENTO_ADQUIRIENTE",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" and C."TaxSum"<>0 AND D."U_IDC_TAFE" IN ('10','11','12','13','14','15','16','17','40') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_GRAVADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('20','21') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_EXONERADAS",
ISNULL((SELECT Case T0."DocCur" WHEN @ML THEN SUM(C."BaseSum") ELSE SUM(C."BaseSumFrg") END 
FROM RIN4 C INNER JOIN RIN1 D ON C."DocEntry" = D."DocEntry" AND C."LineNum" = D."LineNum" 
WHERE C."DocEntry"= T0."DocEntry" AND D."U_IDC_TAFE" IN ('30','31','32','33','34','35','36') AND C."RelateType" IN (1,2,3) 
GROUP BY C."DocEntry"),0.00) "FE_TOTAL_INAFECTAS",
0.00 "FE_TOTAL_GRATUITAS",
0.00 "FE_TOTAL_OTROS_CARGOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DiscSum" ELSE T0."DiscSumFC" END "FE_TOTAL_DESCUENTOS",
0.00 "FE_TOTAL_ISC",
ISNULL((SELECT ISNULL(( SUM ( CASE TX3."DocCur" WHEN @ML THEN TX0."TaxSum" ELSE TX0."TaxSumFrgn" END)),0) 
FROM RIN4 TX0 
INNER JOIN OSTA TX1 ON TX0."StaCode" = TX1."Code"				 
INNER JOIN OINV TX3 ON TX3."DocEntry" = TX0."DocEntry"
LEFT JOIN RIN1 TX2 ON TX0."DocEntry" = TX2."DocEntry" AND TX0."LineNum" = TX2."LineNum" AND TX0."RelateType" IN (1,2,3) WHERE TX3."DocEntry"=T0."DocEntry" AND TX2."U_IDC_TAFE" IN ('10','40') GROUP BY TX0."DocEntry",TX2.U_IDC_TAFE),0.00) "FE_TOTAL_IGV",
0.00 "FE_TOTAL_OTROS_TRIBUTOS",
CASE WHEN T0."DocCur"=@ML THEN T0."DocTotal" ELSE T0."DocTotalFC" END "FE_IMPORTE_TOTAL",
T3."ISOCurrCod" "FE_CODIGO_MONEDA",
T0."DocEntry" "FE_DOCENTRY",
T0."ObjType" "FE_OBJTYPE",
CASE WHEN T0.CANCELED='C' THEN '3' WHEN T0.CANCELED='Y' THEN '3' END "FE_ESTADO",
ISNULL(T0.U_BPP_MDTO,'') "FE_TIPO_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDSO,'') "FE_SERIE_DOCUMENTO_AFECTADO",
ISNULL(T0.U_BPP_MDCO,'') "FE_CORRELATIVO_DOCUMENTO_AFECTADO"
FROM ORIN T0 
INNER JOIN OCRD T1 ON T0."CardCode" = T1."CardCode"
INNER JOIN OCRN T3 ON T3."CurrCode" = T0."DocCur"
INNER JOIN RIN1 T4 ON T0.DocEntry=T4.DocEntry
INNER JOIN ORIN T5 ON T4.BaseEntry=T5.DocEntry
INNER JOIN "@BPP_LPET" T6 ON T5.DocEntry=T6.U_BPP_DOCENTRYNC AND T5.U_BPV_SERI=T6.U_BPP_SERIENC
WHERE T0."DocDate"= CONVERT(date, @Fecha) AND LEFT(T0.U_BPP_MDSD,1)='B' AND T0.CANCELED IN ('C') AND T0.U_BPP_MDTD IN ('03','07','08') AND T0.U_IDC_FESTADO  IN ('BP')
*/
) TA
; 

END