CREATE PROCEDURE IDC_FE_EXTRACCION_ANTICIPO 
(@ObjType varchar(15), @DocEntry int)
AS BEGIN

DECLARE @ML nvarchar(3);

SELECT TOP 1 @ML = T0."MainCurncy" 
FROM OADM T0 INNER JOIN ADM1 T1 ON T0."Code" = T1."Code";

SELECT 
T4.U_BPP_MDTD+T4.U_BPP_MDSD+'-'+RIGHT('00000000' + Ltrim(Rtrim(T4.U_BPP_MDCD)),8)  "FE_ID",
ROW_NUMBER() OVER (ORDER BY T1.U_BPP_MDTD+T1.U_BPP_MDSD+'-'+T1.U_BPP_MDCD) "FE_ANTICIPOID",
T1.U_BPP_MDSD "FE_SERIE",
RIGHT('00000000' + Ltrim(Rtrim(T1.U_BPP_MDCD)),8)   "FE_CORRELATIVO",
'02' AS FE_TIPODOCUMENTO,
CASE WHEN T1."DocCur" = @ML THEN T0."DrawnSum" ELSE T0."DrawnSumFc" END "FE_MONTOANTICIPADO",
T3."TaxIdNum" "FE_DOCUMENTOIDENTIDAD",
'6' AS "FE_TIPODOUMENTOIDENTIDAD",
T2."ISOCurrCod" AS "FE_CODIGO_MONEDA",
'' "FE_TIPO_ANTICIPO"
FROM INV9 T0 INNER JOIN ODPI T1 ON T0."BaseAbs"=T1."DocEntry" 
			 INNER JOIN OCRN T2 ON T1."DocCur"=T2."CurrCode"
			 INNER JOIN OINV T4 ON T0.DocEntry=T4.DocEntry,
			 OADM T3 
WHERE T0."DocEntry"=@DocEntry  AND T0."ObjCode"=@ObjType;

END