CREATE PROCEDURE IDC_FE_EXTRACCION_LISTA_RESUMEN
AS BEGIN

SELECT DISTINCT TT."U_FEC_EMI" FROM
(
/************************************************************* DOCUMENTOS EMITIDOS  *************************************************************/
SELECT DISTINCT
T0."DocDate" "U_FEC_EMI"
FROM OINV T0 WHERE (LEFT(T0."U_BPP_MDSD",1)='B') AND T0.U_IDC_FESTADO='BP' AND T0.U_BPP_MDTD IN ('03','07','08') --AND T0.CANCELED IN ('N')
UNION ALL
SELECT DISTINCT
T0."DocDate" "U_FEC_EMI"
FROM ORIN T0 WHERE (LEFT(T0."U_BPP_MDSD",1)='B') AND T0.U_IDC_FESTADO='BP' AND T0.U_BPP_MDTD IN ('03','07','08') --AND T0.CANCELED IN ('N') 
UNION ALL
SELECT DISTINCT
T0."DocDate" "U_FEC_EMI"
FROM ODPI T0 WHERE  (LEFT(T0."U_BPP_MDSD",1)='B') AND T0.U_IDC_FESTADO='BP' AND T0.U_BPP_MDTD IN ('03','07','08') --AND T0.CANCELED IN ('N') 
UNION ALL
SELECT DISTINCT
T0."DocDate" "U_FEC_EMI"
FROM OINV T0 WHERE (LEFT(T0."U_BPP_MDSD",1)='B') AND T0.U_IDC_FESTADO='RP' AND T0.U_BPP_MDTD IN ('03','07','08') --AND T0.CANCELED IN ('N')
UNION ALL
SELECT DISTINCT
T0."DocDate" "U_FEC_EMI"
FROM ORIN T0 WHERE (LEFT(T0."U_BPP_MDSD",1)='B') AND T0.U_IDC_FESTADO='RP' AND T0.U_BPP_MDTD IN ('03','07','08') --AND T0.CANCELED IN ('N') 
UNION ALL
SELECT DISTINCT
T0."DocDate" "U_FEC_EMI"
FROM ODPI T0 WHERE  (LEFT(T0."U_BPP_MDSD",1)='B') AND T0.U_IDC_FESTADO='RP' AND T0.U_BPP_MDTD IN ('03','07','08') --AND T0.CANCELED IN ('N') 

/*************************************************************  DOCUMENTOS CANCELADOS  *************************************************************/
/*
UNION ALL

SELECT DISTINCT T2.DocDate
FROM OINV T0
INNER JOIN INV1 T1 ON T0.DocEntry=T1.DocEntry
INNER JOIN OINV T2 ON T1.BaseEntry=T2.DocEntry
WHERE (LEFT(T0."U_BPP_MDSD",1)='B' OR T0.U_IDC_ESCONTINGENCIA='Y') AND T0.U_IDC_FESTADO='RP' AND T0.U_BPP_MDTD IN ('03','07','08')  AND T0.CANCELED IN ('C')

UNION ALL

SELECT DISTINCT T2.DocDate
FROM ODPI T0
INNER JOIN DPI1 T1 ON T0.DocEntry=T1.DocEntry
INNER JOIN ODPI T2 ON T1.BaseEntry=T2.DocEntry
WHERE (LEFT(T0."U_BPP_MDSD",1)='B' OR T0.U_IDC_ESCONTINGENCIA='Y') AND T0.U_IDC_FESTADO='RP' AND T0.U_BPP_MDTD IN ('03','07','08')  AND T0.CANCELED IN ('C')

UNION ALL

SELECT DISTINCT T2.DocDate
FROM ORIN T0
INNER JOIN RIN1 T1 ON T0.DocEntry=T1.DocEntry
INNER JOIN ORIN T2 ON T1.BaseEntry=T2.DocEntry
WHERE (LEFT(T0."U_BPP_MDSD",1)='B' OR T0.U_IDC_ESCONTINGENCIA='Y') AND T0.U_IDC_FESTADO='RP' AND T0.U_BPP_MDTD IN ('03','07','08')  AND T0.CANCELED IN ('C')
*/
) TT WHERE CONVERT(VARCHAR(8), GETDATE(), 112)<>CONVERT(VARCHAR(8), "U_FEC_EMI", 112) AND "U_FEC_EMI">='20190401' ORDER BY "U_FEC_EMI" ASC;


END