CREATE PROCEDURE IDC_DOC_DOCUMENTOS_PENDIENTES

AS BEGIN



	DECLARE @TABLA AS TABLE (
[DOCENTRY]					int,	
		[OBJTYPE]					int,
		[CODIGO_BODEGA]				varchar(100),
		[CODIGO_CLIENTE]			varchar(100),	
		[CANTIDAD_LINEAS]			varchar(100),
		[CANTIDAD_TRANSACCIONES] 	varchar(100),
		[TIPO_TRANSACCION]			varchar(100),
		[ESTADO]					varchar(100),
		[NOMBRE_CLIENTE]			varchar(100),
		[DIRECCION_CLIENTE]			varchar(MAX),
		[FECHA_TRASLADO]			varchar(100)
	)

	INSERT INTO @TABLA EXEC [IDC_DOC_EXTRACCION_CABECERA] 
	SELECT 
		[DOCENTRY]					,	
		[OBJTYPE]					,
		[CODIGO_BODEGA]				,
		[CODIGO_CLIENTE]			,	
		[CANTIDAD_LINEAS]			,
		[CANTIDAD_TRANSACCIONES] 	,
		[TIPO_TRANSACCION]			,
		[ESTADO]					,
		[NOMBRE_CLIENTE]			,
		[DIRECCION_CLIENTE]			,
		[FECHA_TRASLADO]			
		
	FROM @TABLA T0 WHERE T0."ESTADO"='PE';


END