CREATE PROCEDURE IDC_FE_EXTRACCION_COMUNICACION_BAJA_DETALLE
AS BEGIN


SELECT TOP 1 * FROM  
(

SELECT
'' "FE_ID",
1 "LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8)  "FE_CORRELATIVO_DOCUMENTO",
'ERROR' "FE_DESCRIPCION",
T0."ObjType" "FE_OBJTYPE",
T0."DocEntry" "FE_DOCENTRY"
FROM OINV T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='F'

UNION ALL

SELECT
'' "FE_ID",
1 "LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8)  "FE_CORRELATIVO_DOCUMENTO",
'ERROR' "FE_DESCRIPCION",
T0."ObjType" "FE_OBJTYPE",
T0."DocEntry" "FE_DOCENTRY"
FROM ORIN T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='F'

UNION ALL

SELECT
'' "FE_ID",
1 "LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8)  "FE_CORRELATIVO_DOCUMENTO",
'ERROR' "FE_DESCRIPCION",
T0."ObjType" "FE_OBJTYPE",
T0."DocEntry" "FE_DOCENTRY"
FROM ODPI T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='F'

UNION ALL

SELECT
'' "FE_ID",
1 "LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8)  "FE_CORRELATIVO_DOCUMENTO",
'ERROR' "FE_DESCRIPCION",
T0."ObjType" "FE_OBJTYPE",
T0."DocEntry" "FE_DOCENTRY"
FROM ODLN T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='T'

UNION ALL

SELECT
'' "FE_ID",
1 "LINEA_ID",
T0.U_BPP_MDTD "FE_TIPO_DOCUMENTO",
T0.U_BPP_MDSD "FE_SERIE_DOCUMENTO",
RIGHT('00000000' + Ltrim(Rtrim(T0.U_BPP_MDCD)),8)  "FE_CORRELATIVO_DOCUMENTO",
'ERROR' "FE_DESCRIPCION",
T0."ObjType" "FE_OBJTYPE",
T0."DocEntry" "FE_DOCENTRY"
FROM OWTR T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='T'

) T;




END