CREATE PROCEDURE IDC_DOC_EXTRACCION_LINEA
@ObjType varchar(15), 
@DocEntry int
AS BEGIN

DECLARE @CANTIDAD_LINEA VARCHAR(4);
DECLARE @CANTIDAD_LINEA_2 VARCHAR(4);

SET @CANTIDAD_LINEA = RIGHT('0000'+ CAST ((SELECT COUNT(BB.LINEA) FROM (SELECT (1) AS LINEA FROM RDR1 TX1 WHERE TX1."DocEntry"=@DocEntry  AND TX1."ObjType" =@ObjType  GROUP BY TX1."ItemCode" ) BB)AS VARCHAR(4)),4)   ;

SET @CANTIDAD_LINEA_2 = RIGHT('0000'+ CAST ((SELECT COUNT(BB.LINEA) FROM (SELECT (1) AS LINEA FROM WTQ1 TX1 WHERE TX1."DocEntry"=@DocEntry  AND TX1."ObjType" =@ObjType  GROUP BY TX1."ItemCode" ) BB)AS VARCHAR(4)),4)   ;





SELECT 
		TT.CORRELATIVO_TRANSACCION		,				
		TT.NUMERO_DOCUMENTO_RESPALDO		,
		TT.RUC_CLIENTE					,
		TT.FECHA							,					
		TT.CODIGO_ARTICULO				,
		TT.NOMBRE_ARTICULO				,
		TT.ID_ADICIONAL_ARTICULO				,
		TT.CANTIDAD						,
		TT.CODIGO_LOCAL					,
		TT.CODIGO_LOTE					,
		TT.DOCENTRY						,
		TT.OBJTYPE						
	FROM (
SELECT 
(RIGHT('0000'+(T1.LineNum),4)) AS "CORRELATIVO_TRANSACCION",
T3."DocEntry" AS "NUMERO_DOCUMENTO_RESPALDO",
T4."LicTradNum" AS "RUC_CLIENTE",
CONVERT(VARCHAR,T3."DocDate",103) AS "FECHA",
T5.ItemName "NOMBRE_ARTICULO",
ISNULL(T5.SWW,'') "ID_ADICIONAL_ARTICULO",
T1."ItemCode" AS "CODIGO_ARTICULO",
(CAST(T1."Quantity" AS INT)) AS "CANTIDAD",
'' AS "CODIGO_LOCAL",
'' AS "CODIGO_LOTE",
T3."DOCENTRY" AS "DOCENTRY",
T3."OBJTYPE" AS "OBJTYPE"
FROM RDR1 T1 
INNER JOIN ORDR T3 ON T1."DocEntry" = T3."DocEntry"
INNER JOIN OCRD T4 ON T3."CardCode" = T4."CardCode"
INNER JOIN OITM T5 ON T5."ItemCode"  = T1."ItemCode"
WHERE T3."DocEntry" = @DocEntry and T3."ObjType" = @ObjType
--GROUP BY T1."ItemCode",T3."DocEntry",T3."OBJTYPE",T3."DocDate",T4."LicTradNum"

UNION ALL

SELECT 
(RIGHT('0000'+(T1.LineNum),4)) AS "CORRELATIVO_TRANSACCION",
T3."DocEntry" AS "NUMERO_DOCUMENTO_RESPALDO",
ISNULL(T4."LicTradNum",'') AS "RUC_CLIENTE",
CONVERT(VARCHAR,T3."DocDate",103) AS "FECHA",
T5.ItemName "NOMBRE_ARTICULO",
ISNULL(T5.SWW,'') "ID_ADICIONAL_ARTICULO",
T1."ItemCode" AS "CODIGO_ARTICULO",
(CAST(T1."Quantity" AS INT)) AS "CANTIDAD",
T1.WhsCode AS "CODIGO_LOCAL",
'' AS "CODIGO_LOTE",
T3."DOCENTRY" AS "DOCENTRY",
T3."OBJTYPE" AS "OBJTYPE"
FROM WTQ1 T1 
INNER JOIN OWTQ T3 ON T1."DocEntry" = T3."DocEntry"
LEFT JOIN OCRD T4 ON T3."CardCode" = T4."CardCode"
INNER JOIN OITM T5 ON T5.ItemCode=T1.ItemCode
WHERE T3."DocEntry" = @DocEntry and T3."ObjType" = @ObjType
--GROUP BY T1."ItemCode",T3."DocEntry",T3."OBJTYPE",T3."DocDate",T4."LicTradNum"
) TT






END