CREATE PROCEDURE IDC_FE_EXTRACCION_RESUMEN_DIARIO_CABECERA
(@Fecha NVARCHAR(50))
AS BEGIN

SELECT
'' "FE_ID",
CAST(@Fecha AS DATE) "FE_FECHA_EMISION",
CAST(@Fecha AS DATE) "FE_FECHA_GENERACION",
T0."TaxIdNum" "FE_RUC_EMISOR",
T0."CompnyName" "FE_RAZON_SOCIAL",
'6' "FE_TIPO_DOCUMENTO_EMISOR",
'' "FE_NUMERO_TICKET",
'' "FE_ESTADO",
'' "FE_RUTA_XML",
'' "FE_RUTA_CDR",
'' "FE_RESPUESTA",
'' "FE_FECHAENVIO",
'' "FE_FECHARESPUESTASUNAT"
FROM OADM T0 
INNER JOIN ADM1 T1 ON T0."Code" = T1."Code"
LEFT JOIN OCST T2 ON T1."State" = T2."Code" AND T0."Country" = T2."Country";

END