CREATE PROCEDURE IDC_DOC_EXTRACCION_CABECERA
AS BEGIN



SELECT 
T0."DocEntry" AS  "DOCENTRY",
T0."ObjType" AS  "OBJTYPE",
(SELECT TOP 1 TX1."WhsCode" FROM RDR1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType"  GROUP BY TX1."WhsCode") AS "CODIGO_BODEGA",
ISNULL(T0."LicTradNum",'')  AS "CODIGO_CLIENTE",
(SELECT RIGHT('0000'+ CAST (COUNT(1) AS VARCHAR(4)),4)  FROM RDR1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") AS "CANTIDAD_LINEAS",
RIGHT('0000'+'1',4) AS "CANTIDAD_TRANSACCIONES",
'OD'  AS "TIPO_TRANSACCION",
T0."U_IDC_IT_FESTADO"  AS "ESTADO",
T0."CardName" "NOMBRE_CLIENTE",
REPLACE(REPLACE(T0.Address2 ,CHAR(13),' '),CHAR(10),' ') "DIRECCION_CLIENTE",
CONVERT(varchar,T0.DocDate,103) "FECHA_DESPACHO"

FROM ORDR T0
--INNER JOIN INV1 T1 ON  T0."DocEntry" =  T1."DocEntry" AND T1."VisOrder" = 0

WHERE T0.U_IDC_IT_FESTADO IN('PE','DS') 


UNION ALL

SELECT 

T0."DocEntry" AS  "DOCENTRY",
T0."ObjType" AS  "OBJTYPE",
(SELECT TOP 1 TX1."FromWhsCod" FROM WTQ1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType" ) AS "CODIGO_BODEGA",
ISNULL(T0."LicTradNum",'')  AS "CODIGO_CLIENTE",
(SELECT RIGHT('0000'+ CAST (COUNT(1) AS VARCHAR(4)),4)  FROM WTQ1 TX1 WHERE TX1."DocEntry"=T0."DocEntry" AND TX1."ObjType" = T0."ObjType") AS "CANTIDAD_LINEAS",
RIGHT('0000'+'1',4) AS "CANTIDAD_TRANSACCIONES",
'OR'  AS "TIPO_TRANSACCION",
T0."U_IDC_IT_FESTADO"  AS "ESTADO",
ISNULL(T0."CardName",'') "NOMBRE_CLIENTE",
(SELECT TOP 1 CONCAT(Tx2.Street,' ',Tx2.StreetNo,' ',tx2.Block) FROM WTQ1 TX1 INNER JOIN OWHS TX2 ON TX1.WhsCode=TX2.WhsCode WHERE TX1.DocEntry=T0.DocEntry AND TX1.ObjType=T0.ObjType) "DIRECCION_CLIENTE",
CONVERT(varchar,T0.DocDate,103) "FECHA_DESPACHO"
FROM OWTQ T0
--INNER JOIN OCRD T1 ON T0."CardCode"=T1."CardCode"

WHERE T0.U_IDC_IT_FESTADO IN('PE','DS') 



END