CREATE PROCEDURE IDC_FE_EXTRACCION_COMUNICACION_BAJA_CABECERA
AS BEGIN


SELECT TOP 1  * FROM 
(

SELECT
'' "FE_ID",
T0."DocDate" "FE_FECHA_GENERACION" ,
T0."DocDate" "FE_FECHA_EMISION",
T2."TaxIdNum" "FE_RUC_EMISOR",
'6' "FE_TIPO_DOCUMENTO_EMISOR",
T2."PrintHeadr" "FE_RAZON_SOCIAL",
'' "FE_ESTADO",
'' "FE_NUMERO_TICKET",
'' "FE_RUTA_CDR",
'' "FE_RUTA_XML",
'' "FE_RESPUESTA",
'' "FE_FECHAENVIO",
'' "FE_FECHARESPUESTASUNAT"
FROM OINV T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='F'

UNION ALL

SELECT
'' "FE_ID",
T0."DocDate" "FE_FECHA_GENERACION" ,
T0."DocDate" "FE_FECHA_EMISION",
T2."TaxIdNum" "FE_RUC_EMISOR",
'6' "FE_TIPO_DOCUMENTO_EMISOR",
T2."PrintHeadr" "FE_RAZON_SOCIAL",
'' "FE_ESTADO",
'' "FE_NUMERO_TICKET",
'' "FE_RUTA_CDR",
'' "FE_RUTA_XML",
'' "FE_RESPUESTA",
'' "FE_FECHAENVIO",
'' "FE_FECHARESPUESTASUNAT"
FROM ORIN T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='F'

UNION ALL

SELECT
'' "FE_ID",
T0."DocDate" "FE_FECHA_GENERACION" ,
T0."DocDate" "FE_FECHA_EMISION",
T2."TaxIdNum" "FE_RUC_EMISOR",
'6' "FE_TIPO_DOCUMENTO_EMISOR",
T2."PrintHeadr" "FE_RAZON_SOCIAL",
'' "FE_ESTADO",
'' "FE_NUMERO_TICKET",
'' "FE_RUTA_CDR",
'' "FE_RUTA_XML",
'' "FE_RESPUESTA",
'' "FE_FECHAENVIO",
'' "FE_FECHARESPUESTASUNAT"
FROM ODPI T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='F'

UNION ALL

SELECT
'' "FE_ID",
T0."DocDate" "FE_FECHA_GENERACION" ,
T0."DocDate" "FE_FECHA_EMISION",
T2."TaxIdNum" "FE_RUC_EMISOR",
'6' "FE_TIPO_DOCUMENTO_EMISOR",
T2."PrintHeadr" "FE_RAZON_SOCIAL",
'' "FE_ESTADO",
'' "FE_NUMERO_TICKET",
'' "FE_RUTA_CDR",
'' "FE_RUTA_XML",
'' "FE_RESPUESTA",
'' "FE_FECHAENVIO",
'' "FE_FECHARESPUESTASUNAT"
FROM ODLN T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='T'


UNION ALL

SELECT
'' "FE_ID",
T0."DocDate" "FE_FECHA_GENERACION" ,
T0."DocDate" "FE_FECHA_EMISION",
T2."TaxIdNum" "FE_RUC_EMISOR",
'6' "FE_TIPO_DOCUMENTO_EMISOR",
T2."PrintHeadr" "FE_RAZON_SOCIAL",
'' "FE_ESTADO",
'' "FE_NUMERO_TICKET",
'' "FE_RUTA_CDR",
'' "FE_RUTA_XML",
'' "FE_RESPUESTA",
'' "FE_FECHAENVIO",
'' "FE_FECHARESPUESTASUNAT"
FROM OWTR T0,
OADM T2
WHERE T0.CANCELED <> 'C' AND T0.U_IDC_FESTADO='BP' AND LEFT(T0.U_BPP_MDSD,1)='T'

) T ;





END